/*
 * recipes.js — the dishes the pantry can turn into.
 *
 * Each recipe names its ingredients by pantry id (js/pantry.js), which is how
 * the counter knows what a dish still needs, how an ingredient's card knows
 * which dishes it goes into, and how the shelves light up for a dish.
 * Quantities and method are for a real kitchen.
 *
 *   key       the ingredients that make it THIS dish — what a cook reaches for
 *             first. The counter suggests a dish by how many of these are on
 *             it. Salt, pepper and oil are in nearly everything and are left
 *             out of `key` unless they are the point (olive oil is, in the
 *             ladera).
 *   vessel    what the cook-along draws: "pot", "tin" (oven dish) or "bowl"
 *             (nothing is cooked, or it is finished cold).
 *   method    each step, read on the recipe page and walked through in the
 *             cook-along (js/main.js). A step may carry:
 *               why    the reason behind it — the part of a recipe that teaches
 *               prep   { id: "how it is prepared" } — shown on the board, and
 *                      tapped to prepare it
 *               add    ids that go into the vessel at this step (prepared or
 *                      not); their pieces then show in it
 *               heat   0 off, 1 low, 2 medium, 3 high, or "oven"
 *               wait   how long the step takes, in words
 *               sauce  the colour of what is in the vessel after this step
 *   table     what the dish means for a table that cooks without dairy, egg or
 *             gluten, need by need. A missing need means "free as written".
 *   fasting   a nistisimo — cooked without meat, dairy or eggs by tradition.
 */

export const RECIPES = [
  /* ================================================================ soups */
  {
    id: "fasolada",
    name: "Fasolada",
    greek: "Φασολάδα",
    line: "White bean soup with carrot, celery and tomato in plenty of olive oil.",
    story: "Often called the national dish of Greece, and the most ordinary food there is: a pot of beans for a winter weekday, made rich by nothing more than olive oil and patience.",
    serves: "4",
    time: "About 2 hours, once the beans have soaked",
    fasting: true,
    vessel: "pot",
    key: ["beans", "carrot", "celery", "onion", "tomato", "oil"],
    ingredients: [
      { id: "beans", amount: "500 g dried, soaked overnight" },
      { id: "onion", amount: "1 large, chopped" },
      { id: "carrot", amount: "2, in rounds" },
      { id: "celery", amount: "2 stalks with leaves, sliced" },
      { id: "garlic", amount: "2 cloves, sliced" },
      { id: "tomato", amount: "2 ripe, grated — or 1 tbsp paste" },
      { id: "bay", amount: "1 leaf" },
      { id: "oil", amount: "120 ml, and more to finish" },
      { id: "salt", amount: "to taste" },
      { id: "blackpepper", amount: "to taste" },
      { id: "parsley", amount: "a handful, to finish" },
    ],
    method: [
      {
        text: "Drain the soaked beans, cover with fresh water, boil for five minutes and drain again.",
        why: "Many cooks throw away the first water. It takes the foam with it and gives a cleaner-tasting soup.",
        prep: { beans: "boiled and drained" },
        heat: 3,
        wait: "5 min",
      },
      {
        text: "Warm half the oil and soften the onion, carrot, celery and garlic gently for about ten minutes. They should soften, not brown.",
        why: "This is the sweet, quiet base. Browning would give a roast flavour that fasolada does not want.",
        prep: { onion: "chopped", carrot: "in rounds", celery: "sliced", garlic: "sliced" },
        add: ["oil", "onion", "carrot", "celery", "garlic"],
        heat: 1,
        wait: "10 min",
        sauce: "#e8c77a",
      },
      {
        text: "Add the beans, tomato and bay, and water to cover by a couple of fingers.",
        why: "Enough water to cook the beans and become broth — but every extra cup is flavour diluted.",
        prep: { tomato: "grated" },
        add: ["beans", "tomato", "bay"],
        heat: 2,
        sauce: "#e39a5c",
      },
      {
        text: "Simmer gently, lid ajar, for an hour to an hour and a half, until the beans are creamy right through. Salt along the way.",
        why: "A lazy bubble, not a boil: boiled hard, bean skins split and the soup turns to mush before the middles are soft.",
        add: ["salt"],
        heat: 1,
        wait: "1–1½ hours",
        sauce: "#d9763a",
      },
      {
        text: "Off the heat, pour in the rest of the oil, grind over pepper and scatter the parsley.",
        why: "Raw olive oil at the end is what makes it fasolada — it tastes green and peppery in a way cooked oil does not.",
        prep: { parsley: "chopped" },
        add: ["oil", "blackpepper", "parsley"],
        heat: 0,
        sauce: "#d9763a",
      },
    ],
    serve: "With bread, olives and a pickle or two — and very often feta.",
    table: {
      dairy: "The pot is dairy-free. The feta served beside it is not: leave it off, or put it on its own plate.",
      gluten: "The pot is gluten-free. The bread it is eaten with is not: serve it with gluten-free bread, or just a spoon.",
    },
  },
  {
    id: "fakes",
    name: "Fakes",
    greek: "Φακές",
    line: "Brown lentil soup with bay and tomato, finished with a splash of vinegar.",
    story: "The cheapest, quickest pot in the Greek kitchen and, for many people, the taste of a school-day lunch. Ready in under an hour, with no soaking.",
    serves: "4",
    time: "About 1 hour",
    fasting: true,
    vessel: "pot",
    key: ["lentils", "onion", "bay", "vinegar"],
    ingredients: [
      { id: "lentils", amount: "250 g brown or green, rinsed" },
      { id: "onion", amount: "1, chopped" },
      { id: "garlic", amount: "2 cloves, sliced" },
      { id: "carrot", amount: "1, diced (optional)" },
      { id: "paste", amount: "1 tbsp" },
      { id: "bay", amount: "2 leaves" },
      { id: "oil", amount: "80 ml, and more to finish" },
      { id: "vinegar", amount: "1 tbsp, or to taste" },
      { id: "oregano", amount: "a pinch" },
      { id: "salt", amount: "to taste" },
      { id: "blackpepper", amount: "to taste" },
    ],
    method: [
      {
        text: "Rinse the lentils and pick out any little stones.",
        why: "Lentils need no soaking — they are small enough to cook through in forty minutes.",
        prep: { lentils: "rinsed" },
      },
      {
        text: "Soften the onion, garlic and carrot in the oil, then stir in the paste for a minute.",
        why: "A short fry of the paste turns it from tinny to sweet.",
        prep: { onion: "chopped", garlic: "sliced", carrot: "diced" },
        add: ["oil", "onion", "garlic", "carrot", "paste"],
        heat: 2,
        wait: "8 min",
        sauce: "#b8552e",
      },
      {
        text: "Add the lentils, bay and about 1.2 litres of water. Simmer until soft and the soup has thickened.",
        why: "Lentils thicken their own soup as they soften — no flour needed.",
        add: ["lentils", "bay"],
        heat: 1,
        wait: "40–50 min",
        sauce: "#7a5634",
      },
      {
        text: "Salt, then add the vinegar and oregano off the heat. Taste, and add more vinegar if it needs lifting.",
        why: "Vinegar at the end is the whole trick: it cuts the earthiness and makes the soup taste of more than lentils.",
        add: ["salt", "vinegar", "oregano", "blackpepper"],
        heat: 0,
        sauce: "#7a5634",
      },
    ],
    serve: "With bread, olives, and very often a piece of salty fish or feta.",
    table: {
      dairy: "Dairy-free in the bowl; feta on the side for whoever eats it.",
      gluten: "Gluten-free in the bowl; mind the bread.",
    },
  },
  {
    id: "avgolemono",
    name: "Chicken avgolemono",
    greek: "Κοτόσουπα αυγολέμονο",
    line: "Chicken and rice soup made silky with egg and lemon.",
    story: "The soup for a cold, for a new mother, for a grandmother's visit. The trick everyone's yiayia knows is the tempering: hot broth whisked into the eggs a ladle at a time, so they thicken rather than scramble.",
    serves: "4 to 6",
    time: "About 1½ hours",
    fasting: false,
    vessel: "pot",
    key: ["chicken", "eggs", "lemon", "rice"],
    ingredients: [
      { id: "chicken", amount: "1 small whole bird, about 1.5 kg" },
      { id: "onion", amount: "1, halved" },
      { id: "carrot", amount: "2, in chunks" },
      { id: "celery", amount: "1 stalk" },
      { id: "rice", amount: "150 g" },
      { id: "eggs", amount: "2" },
      { id: "lemon", amount: "2, juiced" },
      { id: "salt", amount: "to taste" },
      { id: "blackpepper", amount: "to taste" },
    ],
    method: [
      {
        text: "Cover the chicken with cold water with the onion, carrot and celery, bring slowly to a simmer and skim. Cook gently for about an hour.",
        why: "Starting in cold water and never boiling hard gives a clear broth; skimming takes away the grey foam.",
        prep: { onion: "halved", carrot: "in chunks", celery: "in pieces" },
        add: ["chicken", "onion", "carrot", "celery"],
        heat: 1,
        wait: "1 hour",
        sauce: "#f0deaa",
      },
      {
        text: "Lift out the chicken and vegetables. Strain the broth back into the pot, add the rice and simmer until soft. Shred the meat.",
        why: "The rice cooks in the broth and gives it body. The meat goes back at the end so it does not overcook.",
        add: ["rice", "salt"],
        heat: 2,
        wait: "15–20 min",
        sauce: "#f1e2b8",
      },
      {
        text: "Beat the eggs until frothy, then beat in the lemon juice. Whisking all the time, add hot broth a ladle at a time, four or five ladles.",
        why: "This is tempering: warming the eggs gradually so they thicken instead of scrambling when they meet the pot.",
        prep: { eggs: "beaten", lemon: "juiced" },
        heat: 0,
      },
      {
        text: "Off the heat, pour the egg and lemon back into the pot, stirring. Return the chicken, warm through gently — never let it boil again.",
        why: "Boiled, the egg curdles. Gentle heat keeps it smooth and creamy-looking, with no cream in it at all.",
        add: ["eggs", "lemon", "blackpepper"],
        heat: 1,
        sauce: "#f2e0a0",
      },
    ],
    serve: "Hot, with plenty of black pepper.",
    table: {
      egg: "The egg is the dish here. Make tahinosoupa instead — the Lenten version, with tahini whisked into lemon in place of the eggs, tempered with hot broth just the same.",
    },
  },
  {
    id: "tahinosoupa",
    name: "Tahinosoupa",
    greek: "Ταχινόσουπα",
    line: "The Lenten soup: rice simmered in water, made creamy with tahini and lemon.",
    story: "Avgolemono's fasting twin, eaten on the strict days of Lent when eggs are off the table. Tahini whisked with lemon does the egg's work, and the soup comes out just as silky.",
    serves: "4",
    time: "About 30 minutes",
    fasting: true,
    vessel: "pot",
    key: ["tahini", "lemon", "rice"],
    ingredients: [
      { id: "rice", amount: "150 g" },
      { id: "tahini", amount: "4 tbsp" },
      { id: "lemon", amount: "2, juiced" },
      { id: "salt", amount: "to taste" },
      { id: "blackpepper", amount: "to taste" },
    ],
    method: [
      {
        text: "Bring 1.5 litres of salted water to the boil, add the rice and simmer until very soft.",
        why: "Soft, almost overcooked rice releases starch that gives the soup its body.",
        add: ["rice", "salt"],
        heat: 2,
        wait: "15–20 min",
        sauce: "#efe7d2",
      },
      {
        text: "In a bowl, whisk the tahini with the lemon juice. It will seize and thicken — keep whisking, and add a little cold water until smooth.",
        why: "Tahini tightens when it meets acid. A splash of water loosens it back into a pourable cream.",
        prep: { tahini: "whisked", lemon: "juiced" },
        heat: 0,
      },
      {
        text: "Whisk a few ladles of the hot soup into the tahini, then pour it all back into the pot off the heat and stir.",
        why: "Tempering, exactly as with avgolemono: warmed gradually, it blends smoothly instead of clumping.",
        add: ["tahini", "lemon", "blackpepper"],
        heat: 0,
        sauce: "#e8d5aa",
      },
    ],
    serve: "Hot, with black pepper and an extra squeeze of lemon.",
    table: {
      gluten: "Made with rice, it is gluten-free. Some cooks use orzo or fide noodles, which are wheat.",
    },
  },

  /* ================================================================ ladera */
  {
    id: "revithada",
    name: "Revithada",
    greek: "Ρεβιθάδα",
    line: "Chickpeas baked slowly with a great many onions, olive oil and lemon.",
    story: "From Sifnos, where on Saturday night every household carried its clay pot to the baker's oven, still hot from the bread, and collected it after church on Sunday, silky and golden.",
    serves: "4",
    time: "3 to 4 hours in the oven, almost all of it hands-off",
    fasting: true,
    vessel: "pot",
    key: ["chickpeas", "onion", "lemon", "oil"],
    ingredients: [
      { id: "chickpeas", amount: "500 g dried, soaked overnight" },
      { id: "onion", amount: "2 large, thinly sliced" },
      { id: "oil", amount: "150 ml" },
      { id: "bay", amount: "2 leaves" },
      { id: "lemon", amount: "1, juiced" },
      { id: "salt", amount: "to taste" },
      { id: "blackpepper", amount: "to taste" },
    ],
    method: [
      {
        text: "Drain the chickpeas and put them in a clay pot or heavy casserole with the onions, oil, bay and a good pinch of salt.",
        why: "The onions are not a garnish. Over hours they melt completely and become the sauce.",
        prep: { chickpeas: "drained", onion: "thinly sliced" },
        add: ["chickpeas", "onion", "oil", "bay", "salt"],
        sauce: "#ead9a8",
      },
      {
        text: "Add water to cover by two or three centimetres, put the lid on, and bake at 160 °C.",
        why: "Low, even oven heat all round the pot cooks the chickpeas to silk without ever boiling them hard. On the hob, the gentlest simmer for two hours does nearly as well.",
        heat: "oven",
        wait: "3–4 hours",
        sauce: "#e2b45a",
      },
      {
        text: "Look in once or twice and add a splash of hot water if it is drying out. It should end thick, not soupy.",
        why: "A sealed clay pot loses little water; a metal one with a loose lid loses more. Every pot is different, which is why the recipe says look.",
        heat: "oven",
        sauce: "#e2b45a",
      },
      {
        text: "Stir in the lemon juice just before serving, and taste for salt.",
        why: "Lemon cooked for hours loses its brightness. Added at the end it lifts all that sweet onion.",
        prep: { lemon: "juiced" },
        add: ["lemon", "blackpepper"],
        heat: 0,
        sauce: "#e2b45a",
      },
    ],
    serve: "Warm, not hot, with bread and olives.",
    table: {
      gluten: "Some recipes thicken it with a spoon of flour. It does not need one — crush a ladle of the chickpeas back in. Mind the bread on the table.",
    },
  },
  {
    id: "fasolakia",
    name: "Fasolakia",
    greek: "Φασολάκια λαδερά",
    line: "Green beans and potatoes cooked long and soft in olive oil and tomato.",
    story: "The summer lunch of every Greek household, eaten warm or at room temperature, with the bread doing the work of a spoon. Cooked until the beans are soft and the oil and tomato have become one sauce.",
    serves: "4",
    time: "About 1 hour",
    fasting: true,
    vessel: "pot",
    key: ["greenbeans", "potato", "tomato", "oil"],
    ingredients: [
      { id: "greenbeans", amount: "800 g flat beans, trimmed" },
      { id: "potato", amount: "2, in chunks" },
      { id: "onion", amount: "1, chopped" },
      { id: "garlic", amount: "2 cloves, sliced" },
      { id: "tomato", amount: "3 ripe, grated" },
      { id: "oil", amount: "150 ml" },
      { id: "parsley", amount: "a handful" },
      { id: "salt", amount: "to taste" },
      { id: "blackpepper", amount: "to taste" },
    ],
    method: [
      {
        text: "Soften the onion and garlic in the oil until translucent.",
        prep: { onion: "chopped", garlic: "sliced" },
        add: ["oil", "onion", "garlic"],
        heat: 2,
        wait: "5 min",
        sauce: "#e8c77a",
      },
      {
        text: "Add the beans and stir until they turn bright green and glossy with oil.",
        why: "Coating the beans in the hot oil first is what makes this a ladero — cooked in oil, with the tomato as its only liquid.",
        prep: { greenbeans: "trimmed and halved" },
        add: ["greenbeans"],
        heat: 2,
        wait: "5 min",
        sauce: "#d9c27a",
      },
      {
        text: "Add the potatoes, tomato, salt and a glass of water. Cover and simmer until everything is soft.",
        why: "Long and soft on purpose: Greek green beans are meant to yield, not squeak. Shake the pot instead of stirring so the potatoes stay whole.",
        prep: { potato: "in chunks", tomato: "grated" },
        add: ["potato", "tomato", "salt"],
        heat: 1,
        wait: "40–50 min",
        sauce: "#c8502e",
      },
      {
        text: "Uncover for the last few minutes if it is watery, then stir in the parsley and pepper.",
        why: "The sauce should be thick and glossy: oil and tomato cooked into one.",
        prep: { parsley: "chopped" },
        add: ["parsley", "blackpepper"],
        heat: 0,
        sauce: "#c8502e",
      },
    ],
    serve: "Warm, with bread and a slab of feta.",
    table: {
      dairy: "Leave the feta off, or on its own plate.",
      gluten: "Gluten-free in the pot; mind the bread.",
    },
  },
  {
    id: "spanakorizo",
    name: "Spanakorizo",
    greek: "Σπανακόρυζο",
    line: "Spinach and rice cooked together with spring onion, dill and lemon.",
    story: "A spring dish for when the spinach is everywhere and cheap: a bowl of green rice that is somewhere between a pilaf and a risotto, finished with a lot of lemon.",
    serves: "4",
    time: "About 40 minutes",
    fasting: true,
    vessel: "pot",
    key: ["spinach", "rice", "dill", "lemon", "springonion"],
    ingredients: [
      { id: "spinach", amount: "1 kg, washed and roughly chopped" },
      { id: "rice", amount: "200 g" },
      { id: "springonion", amount: "6, sliced" },
      { id: "onion", amount: "1, chopped" },
      { id: "dill", amount: "a big handful" },
      { id: "lemon", amount: "1, juiced" },
      { id: "oil", amount: "100 ml" },
      { id: "salt", amount: "to taste" },
      { id: "blackpepper", amount: "to taste" },
    ],
    method: [
      {
        text: "Soften the onion and spring onions in the oil.",
        prep: { onion: "chopped", springonion: "sliced" },
        add: ["oil", "onion", "springonion"],
        heat: 2,
        wait: "5 min",
        sauce: "#e0d38a",
      },
      {
        text: "Add the spinach a handful at a time, letting each wilt before the next.",
        why: "A kilo of spinach will not fit at once — but it collapses to a tenth of its size in a minute of heat.",
        prep: { spinach: "washed and chopped" },
        add: ["spinach"],
        heat: 2,
        wait: "5 min",
        sauce: "#6f8f3a",
      },
      {
        text: "Stir in the rice, about 500 ml hot water and salt. Cover and simmer gently until the rice is tender and most of the liquid has gone.",
        why: "It should end a little loose and creamy, not dry — the Greek way with rice.",
        add: ["rice", "salt"],
        heat: 1,
        wait: "18–20 min",
        sauce: "#7d9a45",
      },
      {
        text: "Off the heat, stir in the dill, lemon juice and pepper. Rest five minutes before serving.",
        why: "Dill and lemon both fade with cooking; added last they keep the dish bright.",
        prep: { dill: "chopped", lemon: "juiced" },
        add: ["dill", "lemon", "blackpepper"],
        heat: 0,
        sauce: "#7d9a45",
      },
    ],
    serve: "With lemon wedges, olives — and often feta.",
    table: {
      dairy: "Dairy-free in the pot; feta on the side for whoever eats it.",
    },
  },
  {
    id: "soufico",
    name: "Soufico",
    greek: "Σουφικό",
    line: "Ikaria's summer vegetables layered in one pot and cooked down in olive oil and tomato.",
    story: "From Ikaria, the island known for its long-lived people. Whatever the garden gave in August went into one pot, without a drop of water, and came out as something much more than vegetables.",
    serves: "4",
    time: "About 1½ hours",
    fasting: true,
    vessel: "pot",
    key: ["aubergine", "courgette", "pepper", "potato", "tomato", "oil"],
    ingredients: [
      { id: "aubergine", amount: "2, in thick slices" },
      { id: "courgette", amount: "3, in thick slices" },
      { id: "pepper", amount: "2, in strips" },
      { id: "potato", amount: "2, in thick slices" },
      { id: "onion", amount: "2, sliced" },
      { id: "garlic", amount: "3 cloves, sliced" },
      { id: "tomato", amount: "4 ripe, grated" },
      { id: "oil", amount: "150 ml" },
      { id: "oregano", amount: "a pinch" },
      { id: "salt", amount: "to taste" },
      { id: "blackpepper", amount: "to taste" },
    ],
    method: [
      {
        text: "Cut everything thick. Traditionally each vegetable is then fried in turn in olive oil until golden; for a lighter version, skip that and layer them raw.",
        why: "Frying first gives deeper flavour and silkier aubergine; layering raw is quicker and uses less oil. Both are made on Ikaria.",
        prep: { aubergine: "in thick slices", courgette: "in thick slices", pepper: "in strips", potato: "in thick slices", onion: "sliced", garlic: "sliced" },
      },
      {
        text: "Layer in a wide pot: potatoes on the bottom, then onions and peppers, then aubergine, then courgettes, with garlic and salt between the layers.",
        why: "The slowest-cooking vegetables go nearest the heat and the quickest on top, so everything is done at the same moment.",
        add: ["potato", "onion", "pepper", "aubergine", "courgette", "garlic", "salt"],
        sauce: "#5a3c2c",
      },
      {
        text: "Spread the grated tomato over the top, pour over the oil, and add oregano and pepper. Do not add water.",
        why: "The courgettes and tomatoes give up their own water as they cook. Added water would make it a soup.",
        prep: { tomato: "grated" },
        add: ["tomato", "oil", "oregano", "blackpepper"],
        sauce: "#c8502e",
      },
      {
        text: "Cover and cook on a low heat without stirring — shake the pot now and then instead. Rest before serving.",
        why: "Stirring breaks the layers into mush. A shake keeps the bottom from catching while everything stays whole.",
        heat: 1,
        wait: "45–60 min",
        sauce: "#c8502e",
      },
    ],
    serve: "Warm, with bread, and sometimes crumbled feta on top.",
    table: {
      dairy: "Leave off the feta, or serve it on the side. Good oil and a little salt do the same job.",
      gluten: "Gluten-free in the pot; mind the bread.",
    },
  },

  /* ================================================================= oven */
  {
    id: "gemista",
    name: "Gemista",
    greek: "Γεμιστά",
    line: "Tomatoes and peppers stuffed with herbed rice, baked among potato wedges.",
    story: "The dish of high summer, when the tomatoes are almost bursting. Every family argues about the herbs; everyone agrees the potatoes at the bottom of the tin, soaked in the juices, are the best part.",
    serves: "4",
    time: "About 2 hours",
    fasting: true,
    vessel: "tin",
    key: ["tomato", "pepper", "rice", "mint", "parsley"],
    ingredients: [
      { id: "tomato", amount: "6 large, firm" },
      { id: "pepper", amount: "4" },
      { id: "rice", amount: "200 g" },
      { id: "onion", amount: "1, grated" },
      { id: "garlic", amount: "2 cloves, crushed" },
      { id: "parsley", amount: "a big handful, chopped" },
      { id: "mint", amount: "a handful, chopped" },
      { id: "potato", amount: "3, in wedges" },
      { id: "oil", amount: "150 ml" },
      { id: "salt", amount: "to taste" },
      { id: "blackpepper", amount: "to taste" },
    ],
    method: [
      {
        text: "Slice the tops off the tomatoes and keep them as lids. Scoop out the insides into a bowl and blend or chop them. Cut the tops off the peppers and pull out the seeds.",
        why: "The tomato flesh is not thrown away — it becomes the liquid the rice cooks in.",
        prep: { tomato: "hollowed, insides kept", pepper: "hollowed" },
      },
      {
        text: "Mix the rice with the onion, garlic, herbs, half the tomato pulp, half the oil, salt and pepper.",
        why: "The rice goes in raw: it cooks inside the vegetables, drinking the tomato juice.",
        prep: { onion: "grated", garlic: "crushed", parsley: "chopped", mint: "chopped" },
      },
      {
        text: "Stand the vegetables in a tin, fill them three-quarters full and put on their lids. Tuck potato wedges between them and pour over the rest of the pulp and oil.",
        why: "Only three-quarters full, because the rice swells as it cooks and would push the lids off.",
        prep: { potato: "in wedges" },
        add: ["tomato", "pepper", "rice", "onion", "garlic", "parsley", "mint", "potato", "oil", "salt", "blackpepper"],
        sauce: "#d8603a",
      },
      {
        text: "Bake at 180 °C, covered for the first hour, then uncovered until the tops are browned and the rice is soft.",
        why: "Covered, it steams and the rice cooks through; uncovered, the tops roast and the juices thicken.",
        heat: "oven",
        wait: "1½–2 hours",
        sauce: "#c24a2a",
      },
    ],
    serve: "Warm or at room temperature, often with feta and bread.",
    table: {
      dairy: "Some cooks stir cheese into the filling; this one has none. Feta on the side for whoever eats it.",
      gluten: "Gluten-free in the tin; mind the bread.",
    },
  },
  {
    id: "gigantes",
    name: "Gigantes plaki",
    greek: "Γίγαντες πλακί",
    line: "Giant beans baked in a thick tomato sauce with dill and celery.",
    story: "Meze in every taverna and a main course in every home. Plaki means baked in a tin, and the best part is the jammy sauce at the edges, where it catches.",
    serves: "4 to 6",
    time: "About 3 hours, once the beans have soaked",
    fasting: true,
    vessel: "tin",
    key: ["gigantes", "tomato", "dill", "oil"],
    ingredients: [
      { id: "gigantes", amount: "500 g dried, soaked overnight" },
      { id: "onion", amount: "2, chopped" },
      { id: "garlic", amount: "3 cloves, sliced" },
      { id: "carrot", amount: "1, diced" },
      { id: "celery", amount: "1 stalk, diced" },
      { id: "tomato", amount: "4 ripe, grated — or a 400 g tin" },
      { id: "paste", amount: "1 tbsp" },
      { id: "dill", amount: "a handful" },
      { id: "parsley", amount: "a handful" },
      { id: "oil", amount: "150 ml" },
      { id: "salt", amount: "to taste" },
      { id: "blackpepper", amount: "to taste" },
    ],
    method: [
      {
        text: "Simmer the soaked beans in fresh water until just tender but still whole. Drain, keeping a cup of the water.",
        why: "Giant beans are too big to cook through in the oven alone. Simmered gently first, they finish soft without splitting.",
        prep: { gigantes: "simmered until tender" },
        heat: 1,
        wait: "45–60 min",
      },
      {
        text: "Soften the onion, garlic, carrot and celery in half the oil, then add the tomato, paste and herbs and simmer to a thick sauce.",
        prep: { onion: "chopped", garlic: "sliced", carrot: "diced", celery: "diced", tomato: "grated", dill: "chopped", parsley: "chopped" },
        add: ["oil", "onion", "garlic", "carrot", "celery", "tomato", "paste", "dill", "parsley", "salt"],
        heat: 2,
        wait: "15 min",
        sauce: "#c8452a",
      },
      {
        text: "Fold in the beans with a splash of their water, spread in a tin and pour over the rest of the oil. Bake at 180 °C until the sauce is thick and catching at the edges.",
        why: "The oven reduces the sauce until it clings to the beans, and the edges caramelise.",
        add: ["gigantes", "oil", "blackpepper"],
        heat: "oven",
        wait: "45–60 min",
        sauce: "#b33a22",
      },
    ],
    serve: "Warm or at room temperature, with bread and feta.",
    table: {
      dairy: "Dairy-free in the tin; feta on the side.",
      gluten: "Gluten-free in the tin; mind the bread.",
    },
  },
  {
    id: "briam",
    name: "Briam",
    greek: "Μπριάμ",
    line: "Summer vegetables roasted together in olive oil until soft and sticky.",
    story: "Soufico's cousin from the oven: the same garden vegetables, sliced and tumbled into one tin with plenty of oil, and left alone until the edges blacken a little.",
    serves: "4",
    time: "About 1½ hours",
    fasting: true,
    vessel: "tin",
    key: ["potato", "courgette", "aubergine", "pepper", "tomato", "oil"],
    ingredients: [
      { id: "potato", amount: "3, in slices" },
      { id: "courgette", amount: "3, in thick rounds" },
      { id: "aubergine", amount: "1, in chunks" },
      { id: "pepper", amount: "2, in strips" },
      { id: "onion", amount: "2, in wedges" },
      { id: "garlic", amount: "4 cloves, sliced" },
      { id: "tomato", amount: "4 ripe, grated" },
      { id: "parsley", amount: "a handful" },
      { id: "oil", amount: "150 ml" },
      { id: "oregano", amount: "1 tsp" },
      { id: "salt", amount: "to taste" },
      { id: "blackpepper", amount: "to taste" },
    ],
    method: [
      {
        text: "Cut all the vegetables into pieces of about the same size.",
        why: "Roughly the same size so they cook in the same time — the potatoes a little thinner, because they are slowest.",
        prep: { potato: "in slices", courgette: "in rounds", aubergine: "in chunks", pepper: "in strips", onion: "in wedges", garlic: "sliced" },
      },
      {
        text: "Toss them in a tin with the grated tomato, parsley, oregano, oil, salt and pepper.",
        why: "This much oil is the point: the vegetables roast in it rather than steam.",
        prep: { tomato: "grated", parsley: "chopped" },
        add: ["potato", "courgette", "aubergine", "pepper", "onion", "garlic", "tomato", "parsley", "oregano", "oil", "salt", "blackpepper"],
        sauce: "#d0643a",
      },
      {
        text: "Roast at 190 °C, turning once or twice, until everything is soft and the edges are browned.",
        why: "Briam is done when the liquid has gone and the vegetables start to fry in the oil left behind.",
        heat: "oven",
        wait: "1–1¼ hours",
        sauce: "#b84a26",
      },
    ],
    serve: "Warm or at room temperature, with bread and feta.",
    table: {
      dairy: "Dairy-free in the tin; feta on the side.",
      gluten: "Gluten-free in the tin; mind the bread.",
    },
  },
  {
    id: "lemonates",
    name: "Lemon potatoes",
    greek: "Πατάτες λεμονάτες",
    line: "Potatoes roasted in lemon, olive oil, garlic and oregano until soft inside and golden at the edges.",
    story: "Usually the side dish to a Sunday roast chicken, and frequently the part everyone actually fights over.",
    serves: "4",
    time: "About 1¼ hours",
    fasting: true,
    vessel: "tin",
    key: ["potato", "lemon", "oregano", "oil", "garlic"],
    ingredients: [
      { id: "potato", amount: "1 kg, in thick wedges" },
      { id: "lemon", amount: "2, juiced" },
      { id: "oil", amount: "100 ml" },
      { id: "garlic", amount: "3 cloves, crushed" },
      { id: "oregano", amount: "2 tsp" },
      { id: "salt", amount: "1 tsp" },
      { id: "blackpepper", amount: "to taste" },
    ],
    method: [
      {
        text: "Toss the potatoes in a roasting tin with the lemon juice, oil, garlic, oregano, salt and pepper.",
        why: "Everything coats the potatoes before they go in, so every wedge carries the lemon and herb.",
        prep: { potato: "in wedges", lemon: "juiced", garlic: "crushed" },
        add: ["potato", "lemon", "oil", "garlic", "oregano", "salt", "blackpepper"],
        sauce: "#efd98a",
      },
      {
        text: "Pour in about 250 ml of water, so the liquid comes a little way up the potatoes.",
        why: "The potatoes drink the lemony liquid as they cook, which is what makes them creamy inside rather than just roasted.",
        sauce: "#ecd48a",
      },
      {
        text: "Roast at 200 °C, turning once, until the liquid is gone and the edges are golden.",
        why: "First they braise, then once the liquid has gone they fry in the oil left behind. Add a splash of water if the tin dries out too early.",
        heat: "oven",
        wait: "about 1¼ hours",
        sauce: "#e7c46a",
      },
    ],
    serve: "Beside roast chicken or lamb — or on their own with a salad.",
    table: {},
  },

  /* ================================================================= meat */
  {
    id: "stifado",
    name: "Stifado",
    greek: "Στιφάδο",
    line: "Beef braised for hours with whole small onions, red wine, vinegar and cinnamon.",
    story: "A Sunday dish, though not an expensive one: cheap meat, a mountain of onions and a long, slow afternoon. It is just as often made with rabbit, and by the sea with octopus.",
    serves: "4 to 6",
    time: "About 3 hours, most of it hands-off",
    fasting: false,
    vessel: "pot",
    key: ["beef", "pearl", "wine", "vinegar", "cinnamon", "allspice"],
    ingredients: [
      { id: "beef", amount: "1 kg chuck or shin, in large pieces" },
      { id: "pearl", amount: "1 kg, peeled" },
      { id: "oil", amount: "100 ml" },
      { id: "garlic", amount: "3 cloves, sliced" },
      { id: "paste", amount: "2 tbsp" },
      { id: "tomato", amount: "3 ripe, grated — or a 400 g tin" },
      { id: "wine", amount: "200 ml dry red" },
      { id: "vinegar", amount: "50 ml" },
      { id: "cinnamon", amount: "1 stick" },
      { id: "allspice", amount: "6 berries" },
      { id: "cloves", amount: "3" },
      { id: "bay", amount: "2 leaves" },
      { id: "salt", amount: "to taste" },
      { id: "blackpepper", amount: "to taste" },
    ],
    method: [
      {
        text: "Blanch the small onions for a minute, cool them, trim the root end without cutting it off, and slip off the skins.",
        why: "The root end holds each onion together through two hours of simmering.",
        prep: { pearl: "blanched and peeled" },
      },
      {
        text: "Pat the meat dry and brown it in half the oil, in batches, until deep brown on every side. Lift it out.",
        why: "Browning is where the flavour of the sauce comes from. Crowd the pot and the meat steams grey in its own juice instead.",
        prep: { beef: "in large pieces, patted dry" },
        heat: 3,
        wait: "15 min",
      },
      {
        text: "Brown the onions whole in the rest of the oil until golden in patches, and lift them out too. Lower the heat, then stir in the garlic, spices and tomato paste until the paste darkens.",
        why: "Spices warmed in fat release aromas water cannot carry, and fried paste loses its raw edge. Both burn quickly, which is why the heat comes down first.",
        prep: { garlic: "sliced" },
        add: ["oil", "garlic", "cinnamon", "allspice", "cloves", "bay", "paste"],
        heat: 1,
        wait: "2 min",
        sauce: "#9a3322",
      },
      {
        text: "Pour in the wine and vinegar and scrape the bottom. Let it bubble for two minutes.",
        why: "The brown film on the bottom is concentrated flavour; the wine dissolves it into the sauce. The bubbling drives off the sharpest of the alcohol.",
        add: ["wine", "vinegar"],
        heat: 3,
        wait: "2 min",
        sauce: "#6a2420",
      },
      {
        text: "Return the meat with the tomatoes and enough water to just cover. Salt lightly, cover, and keep at the gentlest simmer.",
        why: "A lazy bubble melts the meat's collagen and keeps it juicy; a hard boil squeezes the fibres dry. Salt lightly because the sauce will reduce.",
        prep: { tomato: "grated" },
        add: ["beef", "tomato", "salt"],
        heat: 1,
        wait: "1½ hours",
        sauce: "#842c1f",
      },
      {
        text: "Nestle in the onions and simmer another hour, until the beef yields to a fork and the sauce is thick. Taste, then fish out the cinnamon and bay.",
        why: "Added for the last hour the onions soften but stay whole. At the end, salt for flatness and a pinch of sugar if it is sharp.",
        add: ["pearl", "blackpepper"],
        heat: 1,
        wait: "1 hour",
        sauce: "#7a2a1e",
      },
    ],
    serve: "With rice, potatoes, bread or orzo.",
    table: {
      gluten: "Gluten-free in the pot, as long as nobody dusts the meat in flour (it does not need it) or reaches for a stock cube (it does not need one either, and cubes often hide wheat). Serve it with rice or potatoes rather than bread or orzo.",
    },
  },

  /* ========================================================== meze, cold */
  {
    id: "horiatiki",
    name: "Horiatiki",
    greek: "Χωριάτικη σαλάτα",
    line: "The village salad: tomato, cucumber, onion, pepper and olives, with oregano and olive oil.",
    story: "No lettuce, ever. Made only in summer when the tomatoes are worth eating raw, and served with the oil and juices pooling at the bottom of the bowl — which is what the bread is for.",
    serves: "4",
    time: "10 minutes",
    fasting: false,
    vessel: "bowl",
    key: ["tomato", "cucumber", "redonion", "olives", "oregano"],
    ingredients: [
      { id: "tomato", amount: "4 ripe, in wedges" },
      { id: "cucumber", amount: "1, in thick half-moons" },
      { id: "redonion", amount: "1, in thin rings" },
      { id: "pepper", amount: "1, in rings" },
      { id: "olives", amount: "a handful" },
      { id: "capers", amount: "a spoonful (optional)" },
      { id: "feta", amount: "a slab on top — traditionally" },
      { id: "oregano", amount: "a good pinch" },
      { id: "oil", amount: "4 tbsp, good" },
      { id: "salt", amount: "a pinch" },
    ],
    method: [
      {
        text: "Cut the tomatoes in wedges, the cucumber in thick half-moons, and the onion and pepper in thin rings.",
        why: "Big, rough pieces: this is a salad you eat with a fork and bread, not a chopped salsa.",
        prep: { tomato: "in wedges", cucumber: "in half-moons", redonion: "in thin rings", pepper: "in rings" },
      },
      {
        text: "Put them in a wide bowl with the olives and capers, and salt the tomatoes lightly.",
        why: "Salt draws the juice out of the tomatoes, and that juice mixed with oil becomes the dressing. There is no vinegar.",
        add: ["tomato", "cucumber", "redonion", "pepper", "olives", "capers", "salt"],
        sauce: "#f0e6cf",
      },
      {
        text: "Lay the feta on top in one slab, if it is being eaten, then rub the oregano over between your palms and pour on the oil.",
        why: "Rubbing dried oregano wakes its oils. The feta stays whole so each person breaks off what they want.",
        add: ["oregano", "oil"],
        sauce: "#f0e6cf",
      },
    ],
    serve: "At once, with bread for the juices.",
    table: {
      dairy: "Leave the slab of feta off, or serve it on its own plate. With good tomatoes and plenty of oil and oregano, nothing is missing.",
      gluten: "Gluten-free in the bowl. The bread for the juices is the thing to watch.",
    },
  },
  {
    id: "fava",
    name: "Fava",
    greek: "Φάβα",
    line: "A golden purée of yellow split peas, with raw onion, capers and olive oil on top.",
    story: "On Santorini it is made from a grass pea grown in the island's volcanic soil and is protected by name; everywhere else, yellow split peas. Served warm, smooth as velvet, with everything sharp piled on top.",
    serves: "4",
    time: "About 1 hour",
    fasting: true,
    vessel: "pot",
    key: ["splitpeas", "onion", "capers", "lemon", "oil"],
    ingredients: [
      { id: "splitpeas", amount: "250 g, rinsed" },
      { id: "onion", amount: "1, chopped" },
      { id: "oil", amount: "100 ml, half to finish" },
      { id: "bay", amount: "1 leaf" },
      { id: "lemon", amount: "½, juiced" },
      { id: "redonion", amount: "½, finely chopped, to top" },
      { id: "capers", amount: "1 tbsp, to top" },
      { id: "salt", amount: "to taste" },
    ],
    method: [
      {
        text: "Rinse the split peas well, until the water runs clear.",
        why: "Split peas need no soaking; rinsing takes away the dusty starch that would foam over.",
        prep: { splitpeas: "rinsed" },
      },
      {
        text: "Soften the onion in half the oil, then add the split peas, bay and water to cover by two fingers. Simmer, skimming the foam, until they collapse.",
        why: "They should fall apart completely. Stir now and then near the end, as the purée thickens and wants to catch.",
        prep: { onion: "chopped" },
        add: ["oil", "onion", "splitpeas", "bay"],
        heat: 1,
        wait: "45–60 min",
        sauce: "#ecc24a",
      },
      {
        text: "Take out the bay, salt, and whisk or blend until smooth, adding the lemon. It thickens as it cools.",
        why: "Fava sets like mash once cold, so leave it looser than you want to eat it.",
        prep: { lemon: "juiced" },
        add: ["salt", "lemon"],
        heat: 0,
        sauce: "#f0cc58",
      },
      {
        text: "Spread on a plate, pour over the rest of the oil and scatter with raw onion and capers.",
        why: "Sweet, smooth purée against sharp raw onion and salty capers is the whole dish.",
        prep: { redonion: "finely chopped", capers: "rinsed" },
        add: ["oil", "redonion", "capers"],
        sauce: "#f0cc58",
      },
    ],
    serve: "Warm or at room temperature, as a meze with bread.",
    table: {
      gluten: "Gluten-free on the plate; it is usually scooped up with bread, so offer something else to dip.",
    },
  },
  {
    id: "melitzanosalata",
    name: "Melitzanosalata",
    greek: "Μελιτζανοσαλάτα",
    line: "Smoky aubergine dip with garlic, vinegar, parsley and olive oil.",
    story: "The aubergines are burnt whole over a flame until they collapse, which gives the dip its smoke. Every meze table has one, and every cook guards their own proportions.",
    serves: "4 as a meze",
    time: "About 1 hour",
    fasting: true,
    vessel: "bowl",
    key: ["aubergine", "garlic", "vinegar", "parsley"],
    ingredients: [
      { id: "aubergine", amount: "2 large" },
      { id: "garlic", amount: "1 clove, crushed" },
      { id: "vinegar", amount: "1 tbsp" },
      { id: "lemon", amount: "½, juiced" },
      { id: "parsley", amount: "a handful" },
      { id: "redonion", amount: "a little, grated (optional)" },
      { id: "oil", amount: "80 ml" },
      { id: "salt", amount: "to taste" },
    ],
    method: [
      {
        text: "Char the aubergines whole over a gas flame, under a hot grill or on a barbecue, turning, until the skin is black and they collapse.",
        why: "The burnt skin is what flavours the flesh with smoke. Roasting in the oven alone gives a milder, sweeter dip.",
        prep: { aubergine: "charred and scooped out" },
        heat: 3,
        wait: "30–40 min",
      },
      {
        text: "Scoop the flesh into a colander and let it drain. Chop it finely with a knife.",
        why: "Draining takes away the bitter juice. A knife, not a blender, keeps some texture — a blended one turns gluey.",
        add: ["aubergine"],
        sauce: "#bfa98a",
      },
      {
        text: "Stir in the garlic, vinegar, lemon, onion, parsley and salt, then beat in the oil a little at a time.",
        why: "Adding the oil slowly lets it emulsify into the aubergine, so the dip turns creamy rather than oily.",
        prep: { garlic: "crushed", lemon: "juiced", parsley: "chopped", redonion: "grated" },
        add: ["garlic", "vinegar", "lemon", "redonion", "parsley", "salt", "oil"],
        sauce: "#c9b494",
      },
    ],
    serve: "Cool, as a meze, with bread or raw vegetables.",
    table: {
      dairy: "Some versions add feta or yogurt. This one has none.",
      gluten: "Gluten-free in the bowl; dip raw cucumber and pepper instead of bread.",
    },
  },
  {
    id: "skordalia",
    name: "Skordalia",
    greek: "Σκορδαλιά",
    line: "A thick, fierce garlic and potato dip, sharpened with vinegar.",
    story: "The traditional partner of fried salt cod on the 25th of March, and of beetroot and fried courgettes all year. Made with potato, as here, or with stale bread, which is not gluten-free.",
    serves: "4 as a meze",
    time: "About 40 minutes",
    fasting: true,
    vessel: "bowl",
    key: ["potato", "garlic", "vinegar", "oil"],
    ingredients: [
      { id: "potato", amount: "500 g floury" },
      { id: "garlic", amount: "4 cloves, or more" },
      { id: "vinegar", amount: "2 tbsp" },
      { id: "lemon", amount: "½, juiced" },
      { id: "oil", amount: "120 ml" },
      { id: "salt", amount: "to taste" },
    ],
    method: [
      {
        text: "Boil the potatoes in their skins until soft, then peel while warm.",
        why: "Cooking them whole in the skin keeps them dry and fluffy instead of waterlogged.",
        prep: { potato: "boiled and peeled" },
        heat: 2,
        wait: "20–25 min",
      },
      {
        text: "Pound the garlic to a paste with the salt, then mash in the warm potato.",
        why: "Pound or mash by hand, never blend: potato worked in a blender turns to glue.",
        prep: { garlic: "pounded with salt" },
        add: ["garlic", "salt", "potato"],
        sauce: "#f1e6c6",
      },
      {
        text: "Beat in the oil a little at a time, alternating with the vinegar and lemon, until smooth and thick.",
        why: "Like mayonnaise, the oil goes in slowly so it emulsifies. Taste — skordalia should be properly fierce.",
        prep: { lemon: "juiced" },
        add: ["oil", "vinegar", "lemon"],
        sauce: "#f3eacb",
      },
    ],
    serve: "With fried fish, beetroot or fried vegetables.",
    table: {
      gluten: "Made with potato, it is gluten-free. The bread version, made from soaked stale bread, is not — ask which one you are being served.",
    },
  },
];

export const RECIPE_BY_ID = Object.fromEntries(RECIPES.map((r) => [r.id, r]));

/** The dishes an ingredient goes into, for its card. */
export function dishesWith(id) {
  return RECIPES.filter((r) => r.ingredients.some((i) => i.id === id));
}

/**
 * What the counter could become: every dish with at least one of its key
 * ingredients on the counter, best first. `have` and `missing` are key ids.
 */
export function suggest(counter) {
  const out = [];
  for (const r of RECIPES) {
    const have = r.key.filter((id) => counter.has(id));
    if (!have.length) continue;
    out.push({ recipe: r, have, missing: r.key.filter((id) => !counter.has(id)) });
  }
  return out.sort(
    (a, b) => b.have.length / b.recipe.key.length - a.have.length / a.recipe.key.length || a.missing.length - b.missing.length,
  );
}

/** What a dish contains for this table, from its ingredients. */
export function containsOf(recipe, byId) {
  return [...new Set(recipe.ingredients.flatMap((i) => byId[i.id].contains || []))];
}

export const FASTING_NOTE =
  "A fasting dish. On Orthodox fasting days — more than half the year for the devout — the traditional table goes without meat, dairy and eggs, which is why so much of Greek cooking is dairy-free and egg-free by design.";
