/*
 * recipes.js — the dishes the pantry can turn into.
 *
 * Each recipe names its ingredients by pantry id (js/pantry.js), which is how
 * the counter knows what a dish still needs, how an ingredient's card knows
 * which dishes it goes into, and how the shelves light up for a dish.
 * Quantities and method are for a real kitchen.
 *
 *   key       the ingredients that make it THIS dish — what a cook reaches for
 *             first. The counter suggests a dish by how many of these are on
 *             it. Salt, pepper and oil are in nearly everything and are left
 *             out of `key` unless they are the point (olive oil is, in the
 *             ladera).
 *   vessel    what the cook-along draws: "pot", "tin" (oven dish) or "bowl"
 *             (nothing is cooked, or it is finished cold).
 *   method    each step, read on the recipe page and walked through in the
 *             cook-along (js/main.js). A step may carry:
 *               why    the reason behind it — the part of a recipe that teaches
 *               prep   { id: "how it is prepared" } — shown on the board, and
 *                      tapped to prepare it
 *               add    ids that go into the vessel at this step (prepared or
 *                      not); their pieces then show in it
 *               heat   0 off, 1 low, 2 medium, 3 high, or "oven"
 *               wait   how long the step takes, in words
 *               sauce  the colour of what is in the vessel after this step
 *   table     what the dish means for a table that cooks without dairy, egg or
 *             gluten, need by need. A missing need means "free as written".
 *   fasting   a nistisimo — cooked without meat, dairy or eggs by tradition.
 */

export const RECIPES = [
  /* ================================================================ soups */
  {
    id: "fasolada",
    name: "Fasolada",
    native: "Φασολάδα",
    line: "White bean soup with carrot, celery and tomato in plenty of olive oil.",
    story: "Often called the national dish of Greece, and the most ordinary food there is: a pot of beans for a winter weekday, made rich by nothing more than olive oil and patience.",
    serves: "4",
    time: "About 1½ hours, once the beans have soaked overnight",
    fasting: true,
    vessel: "pot",
    key: ["beans", "carrot", "celery", "onion", "paste", "oil"],
    ingredients: [
      { id: "beans", amount: "300 g dried white beans, soaked overnight" },
      { id: "onion", amount: "1 large, chopped" },
      { id: "carrot", amount: "2, in rounds" },
      { id: "celery", amount: "2 stalks with leaves, sliced" },
      { id: "garlic", amount: "1–2 cloves, sliced (optional)" },
      { id: "paste", amount: "1½ tbsp" },
      { id: "tomato", amount: "1 ripe, grated — or 200 ml passata (optional)" },
      { id: "bay", amount: "1 leaf (optional)" },
      { id: "oil", amount: "90 ml, half to start and half to finish, and more at the table" },
      { id: "salt", amount: "to taste" },
      { id: "blackpepper", amount: "to taste" },
      { id: "lemon", amount: "a squeeze at the table (optional)" },
    ],
    method: [
      {
        text: "Drain the soaked beans and rinse them.",
        why: "A night in water halves the cooking time and helps the beans cook evenly, so the skins stay whole while the middles turn creamy.",
        prep: { beans: "soaked and rinsed" },
      },
      {
        text: "Warm half the oil and soften the onion, carrot, celery and garlic gently for about five minutes. Stir in the paste and let it fry for a minute.",
        why: "The vegetables should soften, not brown: this is a sweet, quiet base. A minute in the oil turns the paste from tinny to sweet.",
        prep: { onion: "chopped", carrot: "in rounds", celery: "sliced", garlic: "sliced" },
        add: ["oil", "onion", "carrot", "celery", "garlic", "paste"],
        heat: 2,
        wait: "6 min",
        sauce: "#d98b4a",
      },
      {
        text: "Add the beans, the tomato and bay if using, and about a litre of water — enough to cover by two fingers. Bring to the boil and skim off the foam.",
        why: "Skimming takes the grey foam away and gives a cleaner soup. Many cooks go further and boil the beans separately first, throwing that water away; most simply skim.",
        prep: { tomato: "grated" },
        add: ["beans", "tomato", "bay"],
        heat: 3,
        wait: "10 min",
        sauce: "#e39a5c",
      },
      {
        text: "Turn it down, set the lid ajar and simmer gently for about an hour, until the beans are soft right through.",
        why: "A lazy bubble, not a boil: boiled hard, bean skins split and the soup turns to mush before the middles are soft.",
        heat: 1,
        wait: "about 1 hour",
        sauce: "#d9763a",
      },
      {
        text: "Season with salt and pepper, pour in the rest of the oil and simmer uncovered for ten to fifteen minutes more, until the broth turns creamy.",
        why: "Salt goes in late, once the beans are soft. The oil bubbling with the beans' starch is what thickens the broth — the creaminess Greek cooks call chylomeni. For more body, mash a ladle of beans against the side.",
        add: ["salt", "blackpepper", "oil"],
        heat: 1,
        wait: "10–15 min",
        sauce: "#d9763a",
      },
      {
        text: "Take it off the heat and let it settle for a few minutes. Serve with a thread of raw olive oil and a squeeze of lemon at the table for whoever wants one.",
        why: "Fasolada thickens as it rests and is better still the next day. Raw oil at the table adds the green, peppery taste that cooked oil loses.",
        prep: { lemon: "in wedges" },
        add: ["lemon"],
        heat: 0,
        sauce: "#d9763a",
      },
    ],
    serve: "With bread, olives and a pickle or two — and very often feta or a salted fish.",
    table: {
      dairy: "The pot is dairy-free. The feta served beside it is not: leave it off, or put it on its own plate.",
      gluten: "The pot is gluten-free. The bread it is eaten with is not: serve it with gluten-free bread, or just a spoon. A few white versions thicken it with flour — this one does not need it.",
    },
  },
  {
    id: "fakes",
    name: "Fakes",
    native: "Φακές",
    line: "Brown lentil soup with tomato and bay, finished with a splash of vinegar.",
    story: "The cheapest, quickest pot in the Greek kitchen and, for many people, the taste of a school-day lunch. Ready in under an hour, with no soaking.",
    serves: "4",
    time: "About 1 hour",
    fasting: true,
    vessel: "pot",
    key: ["lentils", "onion", "tomato", "bay", "vinegar"],
    ingredients: [
      { id: "lentils", amount: "300 g small brown lentils, rinsed" },
      { id: "onion", amount: "1, chopped" },
      { id: "garlic", amount: "2 cloves, sliced" },
      { id: "carrot", amount: "1, diced" },
      { id: "celery", amount: "1 stalk, diced (optional)" },
      { id: "paste", amount: "1 tbsp (optional)" },
      { id: "tomato", amount: "2 ripe, grated — or 250 ml passata" },
      { id: "bay", amount: "2 leaves" },
      { id: "oil", amount: "80 ml, and more at the table" },
      { id: "vinegar", amount: "1–2 tbsp, and more at the table" },
      { id: "oregano", amount: "a pinch (optional)" },
      { id: "salt", amount: "to taste" },
      { id: "blackpepper", amount: "to taste" },
    ],
    method: [
      {
        text: "Rinse the lentils and pick out any little stones.",
        why: "Lentils need no soaking — they are small enough to cook through in forty minutes. Many cooks also bring them to the boil in fresh water and drain them first, for a lighter soup; it is optional.",
        prep: { lentils: "rinsed" },
      },
      {
        text: "Soften the onion, carrot and celery in the oil for about eight minutes, then stir in the garlic and the paste for a minute.",
        why: "A short fry of the paste turns it from tinny to sweet. Garlic goes in last so it does not burn.",
        prep: { onion: "chopped", carrot: "diced", celery: "diced", garlic: "sliced" },
        add: ["oil", "onion", "carrot", "celery", "garlic", "paste"],
        heat: 2,
        wait: "9 min",
        sauce: "#b8552e",
      },
      {
        text: "Add the lentils, the tomato, the bay and about 1.1 litres of hot water. Cover and simmer gently until the lentils are soft and the soup has thickened, salting halfway.",
        why: "Lentils thicken their own soup as they soften — no flour needed. With the lid on, the water stays in the pot rather than in the kitchen.",
        prep: { tomato: "grated" },
        add: ["lentils", "tomato", "bay", "salt"],
        heat: 1,
        wait: "40–45 min",
        sauce: "#7a5634",
      },
      {
        text: "Off the heat, stir in the vinegar, the oregano and a grind of pepper. Taste, and add more vinegar if it needs lifting. Serve with more oil and vinegar on the table.",
        why: "Vinegar at the end is the whole trick: it cuts the earthiness and makes the soup taste of more than lentils. Everyone likes a different amount, which is why the bottle goes on the table too.",
        add: ["vinegar", "oregano", "blackpepper"],
        heat: 0,
        sauce: "#7a5634",
      },
    ],
    serve: "With bread, olives, and very often a piece of salty fish or feta.",
    table: {
      dairy: "Dairy-free in the bowl; feta on the side for whoever eats it.",
      gluten: "Gluten-free in the bowl; mind the bread.",
    },
  },
  {
    id: "avgolemono",
    name: "Chicken avgolemono",
    native: "Κοτόσουπα αυγολέμονο",
    line: "Chicken and rice soup made silky with egg and lemon.",
    story: "The soup for a cold, for a new mother, for a grandmother's visit. The trick everyone's yiayia knows is the tempering: hot broth whisked into the eggs a ladle at a time, so they thicken rather than scramble.",
    serves: "6",
    time: "About 1¾ hours",
    fasting: false,
    vessel: "pot",
    key: ["chicken", "eggs", "lemon", "rice"],
    ingredients: [
      { id: "chicken", amount: "1 whole bird, about 1.7 kg" },
      { id: "onion", amount: "1, halved" },
      { id: "carrot", amount: "2, in chunks" },
      { id: "celery", amount: "1–2 stalks" },
      { id: "rice", amount: "180 g (about a cup), short or medium grain" },
      { id: "oil", amount: "2 tbsp (optional)" },
      { id: "eggs", amount: "2" },
      { id: "lemon", amount: "2, juiced" },
      { id: "salt", amount: "to taste" },
      { id: "blackpepper", amount: "to taste" },
    ],
    method: [
      {
        text: "Cover the chicken with about 3 litres of cold water, with the onion, carrot and celery and a little salt. Bring slowly to a simmer, skimming off the foam, then cook gently with the lid ajar for about an hour, until the meat comes away from the bone.",
        why: "Starting in cold water and never boiling hard gives a clear broth; skimming in the first minutes takes away the grey foam.",
        prep: { onion: "halved", carrot: "in chunks", celery: "in pieces" },
        add: ["chicken", "onion", "carrot", "celery", "salt"],
        heat: 1,
        wait: "about 1 hour",
        sauce: "#f0deaa",
      },
      {
        text: "Lift out the chicken and vegetables. Strain the broth back into the pot, add the rice and the oil if using, and simmer until the rice is soft. Meanwhile take the meat off the bones and shred it.",
        why: "The rice cooks in the broth and gives it body. The meat goes back at the end so it does not overcook.",
        add: ["rice", "oil"],
        heat: 2,
        wait: "15–20 min",
        sauce: "#f1e2b8",
      },
      {
        text: "Beat the eggs well, then beat in the lemon juice. Whisking all the time, add hot broth a ladle at a time — three or four ladles — until the bowl feels warm.",
        why: "This is tempering: warming the eggs gradually so they thicken instead of scrambling when they meet the pot. Many cooks whip the whites to a soft meringue first and fold in the yolks, for a lighter, frothier soup — just as traditional.",
        prep: { eggs: "beaten", lemon: "juiced" },
        heat: 0,
      },
      {
        text: "Take the pot off the heat and pour in the egg and lemon, stirring. Return the chicken and warm it through on the lowest heat for a minute or two — never let it boil again.",
        why: "Boiled, the egg curdles. Gentle heat keeps it smooth and creamy-looking, with no cream in it at all.",
        add: ["eggs", "lemon", "blackpepper"],
        heat: 1,
        sauce: "#f2e0a0",
      },
    ],
    serve: "Hot, with plenty of black pepper and lemon on the table. Some families serve the chicken on its own plate afterwards.",
    table: {
      egg: "The egg is the dish here. Make tahinosoupa instead — the Lenten version, with tahini whisked into lemon in place of the eggs, tempered with hot broth just the same.",
      gluten: "Made with rice, it is gluten-free. Many cooks use orzo or fide noodles instead, which are wheat.",
    },
  },
  {
    id: "tahinosoupa",
    name: "Tahinosoupa",
    native: "Ταχινόσουπα",
    line: "The Lenten soup: rice simmered in water, made creamy with tahini and lemon.",
    story: "Avgolemono's fasting twin, eaten on the strict days of Lent when eggs are off the table — and on Mount Athos, where it is made without a drop of oil. Tahini whisked with lemon does the egg's work, and the soup comes out just as silky.",
    serves: "4",
    time: "About 35 minutes",
    fasting: true,
    vessel: "pot",
    key: ["tahini", "lemon", "rice"],
    ingredients: [
      { id: "rice", amount: "100 g short-grain" },
      { id: "tahini", amount: "100 g (6–7 tbsp)" },
      { id: "lemon", amount: "2, juiced, and more at the table" },
      { id: "salt", amount: "to taste" },
      { id: "blackpepper", amount: "to taste (optional)" },
    ],
    method: [
      {
        text: "Bring 1.25 litres of salted water to the boil, add the rice and simmer until very soft.",
        why: "Soft, almost overcooked rice releases starch that gives the soup its body.",
        add: ["rice", "salt"],
        heat: 2,
        wait: "20–25 min",
        sauce: "#efe7d2",
      },
      {
        text: "In a big bowl, whisk the tahini and add the lemon juice a little at a time. It will seize into a thick paste — keep whisking.",
        why: "Tahini tightens when it meets acid. That is expected; the hot broth in the next step loosens it again.",
        prep: { tahini: "whisked", lemon: "juiced" },
        heat: 0,
      },
      {
        text: "Whisking all the time, add hot broth from the pot a ladle at a time — about three ladles — until the tahini is as loose as milk.",
        why: "Tempering, exactly as with avgolemono: warmed and thinned gradually, it blends smoothly instead of clumping. Some cooks loosen it with a splash of cold water first; the broth does the same job.",
        heat: 0,
      },
      {
        text: "Take the pot off the heat, pour the tahini back in and stir. Give it a minute on low if you want it thicker, then let it stand for five minutes before serving.",
        why: "Tahini cannot scramble the way egg does, so a moment of heat is safe — but the soup thickens on its own as it stands, and looks thinner in the pot than it will in the bowl.",
        add: ["tahini", "lemon", "blackpepper"],
        heat: 1,
        wait: "5 min",
        sauce: "#e8d5aa",
      },
    ],
    serve: "Hot, with black pepper and an extra squeeze of lemon.",
    table: {
      gluten: "Made with rice, it is gluten-free. Many cooks use orzo, fide or hilopites instead, which are wheat.",
    },
  },

  /* ================================================================ ladera */
  {
    id: "revithada",
    name: "Revithada",
    native: "Ρεβιθάδα",
    line: "Chickpeas baked slowly with a great many onions, olive oil and lemon.",
    story: "From Sifnos, where on Saturday night every household carried its clay pot to the baker's oven, still hot from the bread, and collected it after church on Sunday, silky and golden.",
    serves: "4",
    time: "About 6 hours in the oven, almost all of it hands-off",
    fasting: true,
    vessel: "pot",
    key: ["chickpeas", "onion", "lemon", "oil"],
    ingredients: [
      { id: "chickpeas", amount: "500 g dried, soaked overnight" },
      { id: "onion", amount: "2 large (about 400 g), finely chopped" },
      { id: "oil", amount: "120 ml, and a little more to finish" },
      { id: "bay", amount: "2 leaves" },
      { id: "lemon", amount: "1, juiced, and wedges" },
      { id: "salt", amount: "about 1½ tsp" },
      { id: "blackpepper", amount: "to taste" },
    ],
    method: [
      {
        text: "Drain the chickpeas, rinse them well, and put them in a clay pot or heavy casserole with the onions, oil, bay, salt and pepper. Choose a pot they nearly fill.",
        why: "The onions are not a garnish. Over hours they melt completely and become the sauce. Many cooks add a teaspoon of bicarbonate of soda to the soaked chickpeas for half an hour first, then rinse it away; it softens the skins.",
        prep: { chickpeas: "drained and rinsed", onion: "finely chopped" },
        add: ["chickpeas", "onion", "oil", "bay", "salt", "blackpepper"],
        sauce: "#ead9a8",
      },
      {
        text: "Add water to cover by two or three centimetres. Lay a sheet of foil over the pot, press the lid down on it, and bake at 150 °C.",
        why: "Low, even oven heat all round the pot cooks the chickpeas to silk without ever boiling them hard. On Sifnos the lid is sealed with a rope of flour-and-water dough; foil does the same job without the gluten.",
        heat: "oven",
        wait: "5–6 hours",
        sauce: "#e2b45a",
      },
      {
        text: "Look in once or twice and add a splash of hot water if it is drying out. It should end thick and creamy, not soupy.",
        why: "A sealed clay pot loses little water; a metal one with a loose lid loses more. Every pot is different, which is why the recipe says look.",
        heat: "oven",
        sauce: "#e2b45a",
      },
      {
        text: "Take out the bay leaves. Stir in the lemon juice and a thread of raw olive oil just before serving, and taste for salt.",
        why: "Lemon cooked for hours loses its brightness and can tighten the chickpeas. Added at the end it lifts all that sweet onion.",
        prep: { lemon: "juiced" },
        add: ["lemon"],
        heat: 0,
        sauce: "#e2b45a",
      },
    ],
    serve: "Warm, not hot, with lemon wedges, bread and olives.",
    table: {
      gluten: "The traditional seal round the lid is flour-and-water dough — use foil under the lid instead, as here. Mind the bread on the table.",
    },
  },
  {
    id: "fasolakia",
    name: "Fasolakia",
    native: "Φασολάκια λαδερά",
    line: "Green beans and potatoes cooked long and soft in olive oil and tomato.",
    story: "The summer lunch of every Greek household, eaten warm or at room temperature, with the bread doing the work of a spoon. Cooked until the beans are soft and the oil and tomato have become one sauce.",
    serves: "4",
    time: "About 1 hour, and a rest",
    fasting: true,
    vessel: "pot",
    key: ["greenbeans", "potato", "tomato", "oil"],
    ingredients: [
      { id: "greenbeans", amount: "1 kg, flat ones if you can, trimmed" },
      { id: "potato", amount: "2 large (about 500 g), in chunks" },
      { id: "onion", amount: "1 large, chopped" },
      { id: "garlic", amount: "2 cloves, sliced" },
      { id: "tomato", amount: "3 ripe (about 500 g), grated" },
      { id: "oil", amount: "120 ml" },
      { id: "parsley", amount: "½ bunch" },
      { id: "salt", amount: "to taste" },
      { id: "blackpepper", amount: "to taste" },
    ],
    method: [
      {
        text: "Soften the onion and garlic in the oil until translucent.",
        prep: { onion: "chopped", garlic: "sliced" },
        add: ["oil", "onion", "garlic"],
        heat: 2,
        wait: "5 min",
        sauce: "#e8c77a",
      },
      {
        text: "Add the beans and potatoes and stir until the beans turn bright green and everything is glossy with oil.",
        why: "Coating the vegetables in the hot oil first is what makes this a ladero — cooked in oil, with the tomato as its main liquid.",
        prep: { greenbeans: "trimmed and halved", potato: "in chunks" },
        add: ["greenbeans", "potato"],
        heat: 2,
        wait: "5 min",
        sauce: "#d9c27a",
      },
      {
        text: "Add the tomato, salt and about 250 ml hot water — enough to come halfway up the beans. Cover and simmer until everything is soft.",
        why: "Long and soft on purpose: Greek green beans are meant to yield, not squeak. Shake the pot instead of stirring so the potatoes stay whole. A pinch of sugar is common if the tomatoes are sharp.",
        prep: { tomato: "grated" },
        add: ["tomato", "salt"],
        heat: 1,
        wait: "40–50 min",
        sauce: "#c8502e",
      },
      {
        text: "Uncover for the last few minutes if it is watery, then stir in the parsley and pepper. Rest for 15–30 minutes before serving.",
        why: "It is done when only the oil is left, glossy round the tomato. It tastes better warm than hot, so the rest is part of the dish.",
        prep: { parsley: "chopped" },
        add: ["parsley", "blackpepper"],
        heat: 0,
        wait: "15–30 min",
        sauce: "#c8502e",
      },
    ],
    serve: "Warm or at room temperature, with bread and a slab of feta.",
    table: {
      dairy: "Leave the feta off, or on its own plate.",
      gluten: "Gluten-free in the pot; mind the bread.",
    },
  },
  {
    id: "spanakorizo",
    name: "Spanakorizo",
    native: "Σπανακόρυζο",
    line: "Spinach and rice cooked together with spring onion, dill and lemon.",
    story: "A spring dish for when the spinach is everywhere and cheap: a bowl of green rice that is somewhere between a pilaf and a risotto, finished with a lot of lemon.",
    serves: "4",
    time: "About 45 minutes",
    fasting: true,
    vessel: "pot",
    key: ["spinach", "rice", "dill", "lemon", "springonion"],
    ingredients: [
      { id: "spinach", amount: "750 g, washed and roughly chopped" },
      { id: "rice", amount: "160 g medium grain" },
      { id: "springonion", amount: "4, sliced" },
      { id: "onion", amount: "1, chopped" },
      { id: "dill", amount: "½ bunch" },
      { id: "lemon", amount: "1, juiced, and wedges" },
      { id: "oil", amount: "90 ml" },
      { id: "salt", amount: "to taste" },
      { id: "blackpepper", amount: "to taste" },
    ],
    method: [
      {
        text: "Soften the onion and spring onions in two-thirds of the oil without letting them colour.",
        prep: { onion: "chopped", springonion: "sliced" },
        add: ["oil", "onion", "springonion"],
        heat: 2,
        wait: "5 min",
        sauce: "#e0d38a",
      },
      {
        text: "Add the spinach a handful at a time, letting each wilt before the next.",
        why: "This much spinach will not fit at once — but it collapses to a tenth of its size in a minute of heat.",
        prep: { spinach: "washed and chopped" },
        add: ["spinach"],
        heat: 2,
        wait: "5 min",
        sauce: "#6f8f3a",
      },
      {
        text: "Stir in the rice, about 500 ml hot water and salt. Cover and simmer gently until the rice is tender and most of the liquid has gone.",
        why: "It should end a little loose and creamy, not dry — the Greek way with rice.",
        add: ["rice", "salt"],
        heat: 1,
        wait: "20 min",
        sauce: "#7d9a45",
      },
      {
        text: "Off the heat, stir in the dill, lemon juice, pepper and the rest of the oil. Cover and rest ten minutes before serving.",
        why: "Dill and lemon both fade with cooking; added last they keep the dish bright. The raw oil at the end tastes of olives, not of the pan.",
        prep: { dill: "chopped", lemon: "juiced" },
        add: ["dill", "lemon", "blackpepper"],
        heat: 0,
        wait: "10 min",
        sauce: "#7d9a45",
      },
    ],
    serve: "With lemon wedges, olives — and often feta.",
    table: {
      dairy: "Dairy-free in the pot; feta on the side for whoever eats it.",
    },
  },
  {
    id: "soufico",
    name: "Soufico",
    native: "Σουφικό",
    line: "Ikaria's summer vegetables layered in one pot and cooked down in olive oil and tomato.",
    story: "From Ikaria, the island known for its long-lived people. Whatever the garden gave in August went into one pot, without a drop of water, and came out as something much more than vegetables.",
    serves: "4",
    time: "About 1¼ hours",
    fasting: true,
    vessel: "pot",
    key: ["aubergine", "courgette", "pepper", "potato", "tomato", "oil"],
    ingredients: [
      { id: "aubergine", amount: "2 medium, in thick slices" },
      { id: "courgette", amount: "2, in thick slices" },
      { id: "pepper", amount: "2 green, in strips" },
      { id: "potato", amount: "2, in thick slices" },
      { id: "onion", amount: "2 large, sliced" },
      { id: "garlic", amount: "3 cloves, sliced" },
      { id: "tomato", amount: "3 ripe (about 400 g), grated" },
      { id: "oil", amount: "120 ml" },
      { id: "oregano", amount: "a pinch" },
      { id: "salt", amount: "to taste" },
      { id: "blackpepper", amount: "to taste" },
    ],
    method: [
      {
        text: "Cut everything thick. On Ikaria the vegetables go into the pot raw; for a richer, more festive version, fry each one in turn in olive oil until golden first.",
        why: "Ikarians say nothing fried and no stirring is what makes it soufico rather than briam. Frying first gives deeper flavour and silkier aubergine, at the cost of much more oil and half an hour.",
        prep: { aubergine: "in thick slices", courgette: "in thick slices", pepper: "in strips", potato: "in thick slices", onion: "sliced", garlic: "sliced" },
      },
      {
        text: "Layer in a wide, heavy pot: onions on the bottom, then potatoes, then peppers and aubergine, then courgettes, with garlic and salt between the layers.",
        why: "The onions sweeten and protect the bottom; the slowest-cooking vegetables sit nearest the heat and the quickest on top, so everything is done at the same moment.",
        add: ["onion", "potato", "pepper", "aubergine", "courgette", "garlic", "salt"],
        sauce: "#5a3c2c",
      },
      {
        text: "Spread the grated tomato over the top, pour over the oil, and add oregano and pepper. Do not add water.",
        why: "The courgettes and tomatoes give up their own water as they cook. Added water would make it a soup.",
        prep: { tomato: "grated" },
        add: ["tomato", "oil", "oregano", "blackpepper"],
        sauce: "#c8502e",
      },
      {
        text: "Cover and cook on a low heat without stirring — shake the pot now and then instead — until the potatoes are tender and the juices have cooked down to the oil. Rest before serving.",
        why: "Stirring breaks the layers into mush. A shake keeps the bottom from catching while everything stays whole.",
        heat: 1,
        wait: "40–50 min",
        sauce: "#c8502e",
      },
    ],
    serve: "Warm or at room temperature, with bread, and sometimes crumbled feta on top.",
    table: {
      dairy: "Leave off the feta, or serve it on the side. Good oil and a little salt do the same job.",
      gluten: "Gluten-free in the pot; mind the bread.",
    },
  },

  /* ================================================================= oven */
  {
    id: "gemista",
    name: "Gemista",
    native: "Γεμιστά",
    line: "Tomatoes and peppers stuffed with herbed rice, baked among potato wedges.",
    story: "The dish of high summer, when the tomatoes are almost bursting. Every family argues about the herbs; everyone agrees the potatoes at the bottom of the tin, soaked in the juices, are the best part.",
    serves: "4",
    time: "About 1¾ hours, with a rest",
    fasting: true,
    vessel: "tin",
    key: ["tomato", "pepper", "rice", "mint", "parsley"],
    ingredients: [
      { id: "tomato", amount: "4 large, firm" },
      { id: "pepper", amount: "4" },
      { id: "rice", amount: "160 g medium grain" },
      { id: "onion", amount: "1 large, grated" },
      { id: "garlic", amount: "2 cloves, crushed" },
      { id: "parsley", amount: "½ bunch, chopped" },
      { id: "mint", amount: "½ bunch, chopped" },
      { id: "potato", amount: "2, in wedges" },
      { id: "oil", amount: "150 ml" },
      { id: "salt", amount: "to taste" },
      { id: "blackpepper", amount: "to taste" },
    ],
    method: [
      {
        text: "Slice the tops off the tomatoes and keep them as lids. Scoop out the insides into a bowl and blend or chop them. Cut the tops off the peppers and pull out the seeds. Sprinkle a little salt inside each one.",
        why: "The tomato flesh is not thrown away — it becomes the liquid the rice cooks in.",
        prep: { tomato: "hollowed, insides kept", pepper: "hollowed" },
      },
      {
        text: "Mix the rice with the onion, garlic, herbs, half the tomato pulp, half the oil, salt and pepper. A pinch of sugar helps if the tomatoes are sharp.",
        why: "The rice goes in raw: it cooks inside the vegetables, drinking the tomato juice. Many cooks soften it with the onion and pulp for five minutes first; it is quicker in the oven but must stay underdone.",
        prep: { onion: "grated", garlic: "crushed", parsley: "chopped", mint: "chopped" },
      },
      {
        text: "Stand the vegetables in a tin, fill them three-quarters full and put on their lids. Tuck potato wedges between them, season them, and pour over the rest of the pulp and oil with a small glass of water.",
        why: "Only three-quarters full, because the rice swells as it cooks and would push the lids off. The water keeps the bottom from catching before the vegetables give up their juice.",
        prep: { potato: "in wedges" },
        add: ["tomato", "pepper", "rice", "onion", "garlic", "parsley", "mint", "potato", "oil", "salt", "blackpepper"],
        sauce: "#d8603a",
      },
      {
        text: "Bake at 190 °C under foil for 45 minutes, then uncovered until the tops are browned and the rice is soft. Rest for 15–30 minutes before serving.",
        why: "Covered, it steams and the rice cooks through; uncovered, the tops roast and the juices thicken. Resting lets the rice finish drinking what is left.",
        heat: "oven",
        wait: "1¼ hours, then rest",
        sauce: "#c24a2a",
      },
    ],
    serve: "Warm or at room temperature, often with feta and bread.",
    table: {
      dairy: "Some cooks stir cheese into the filling; this one has none. Feta on the side for whoever eats it.",
      gluten: "Gluten-free in the tin. Some cooks scatter breadcrumbs over the lids — leave them off. Mind the bread.",
    },
  },
  {
    id: "gigantes",
    name: "Gigantes plaki",
    native: "Γίγαντες πλακί",
    line: "Giant beans baked in a thick tomato sauce with carrot, celery and parsley.",
    story: "Meze in every taverna and a main course in every home. Plaki means baked in a tin, and the best part is the jammy sauce at the edges, where it catches.",
    serves: "4 to 6",
    time: "About 2½ hours, once the beans have soaked",
    fasting: true,
    vessel: "tin",
    key: ["gigantes", "tomato", "oil", "parsley"],
    ingredients: [
      { id: "gigantes", amount: "500 g dried, soaked overnight" },
      { id: "onion", amount: "2, chopped" },
      { id: "garlic", amount: "3 cloves, sliced" },
      { id: "carrot", amount: "2, diced" },
      { id: "celery", amount: "2 stalks, diced" },
      { id: "tomato", amount: "600 g ripe (about 4), grated — or a 400 g tin plus 2 fresh" },
      { id: "paste", amount: "2 tbsp" },
      { id: "parsley", amount: "a handful" },
      { id: "oregano", amount: "1 tsp dried" },
      { id: "dill", amount: "a handful (optional)" },
      { id: "oil", amount: "125 ml" },
      { id: "salt", amount: "to taste" },
      { id: "blackpepper", amount: "to taste" },
    ],
    method: [
      {
        text: "Simmer the soaked beans in fresh water until nearly tender but still whole. Drain, keeping the cooking water.",
        why: "Giant beans are too big to cook through in the oven alone. Simmered gently first, they finish soft in the sauce without splitting — so stop while they still have a little bite.",
        prep: { gigantes: "simmered until nearly tender" },
        heat: 1,
        wait: "45–60 min",
      },
      {
        text: "Soften the onion, garlic, carrot and celery in half the oil. Stir in the tomato paste for a minute, then add the tomato, parsley, oregano and the dill if you are using it, season, and simmer to a thick sauce.",
        why: "Paste fried for a moment in the oil loses its raw edge. If the tomatoes taste sharp, a pinch of sugar is what most Greek cooks add here.",
        prep: { onion: "chopped", garlic: "sliced", carrot: "diced", celery: "diced", tomato: "grated", parsley: "chopped", dill: "chopped" },
        add: ["oil", "onion", "garlic", "carrot", "celery", "paste", "tomato", "parsley", "oregano", "dill", "salt"],
        heat: 2,
        wait: "15 min",
        sauce: "#c8452a",
      },
      {
        text: "Fold in the beans, spread them in a tin, and pour in about 250 ml of their cooking water — enough to come just up to the top of the beans. Pour the rest of the oil over.",
        why: "The beans drink this liquid in the oven, which is what makes them creamy. Too little and they bake dry before they soften.",
        add: ["gigantes", "oil", "blackpepper"],
        sauce: "#c4442a",
      },
      {
        text: "Bake uncovered at 180 °C until the liquid has gone, the sauce has thickened down to its oil and the top and edges catch. Add a splash of hot water if it dries out before the beans are soft.",
        why: "The oven reduces the sauce until it clings to the beans, and the edges caramelise. If your beans went in firm, cover the tin for the first half hour.",
        heat: "oven",
        wait: "1–1¼ hours",
        sauce: "#b33a22",
      },
    ],
    serve: "Warm or at room temperature, with bread and feta.",
    table: {
      dairy: "Dairy-free in the tin — some cooks bake feta on top; keep it on the side.",
      gluten: "Gluten-free in the tin; mind the bread, and skip the stock cube some recipes add (cubes often hide wheat).",
    },
  },
  {
    id: "briam",
    name: "Briam",
    native: "Μπριάμ",
    line: "Summer vegetables baked together in olive oil and tomato until soft and sticky.",
    story: "Soufico's cousin from the oven: the same garden vegetables, cut up and tumbled into one tin with plenty of oil, baked under a lid of foil until soft, then left uncovered until the edges blacken a little.",
    serves: "4",
    time: "About 1¾ hours",
    fasting: true,
    vessel: "tin",
    key: ["potato", "courgette", "aubergine", "pepper", "tomato", "oil"],
    ingredients: [
      { id: "potato", amount: "500 g (2–3), in slices" },
      { id: "courgette", amount: "2, in thick rounds" },
      { id: "aubergine", amount: "1 large (about 400 g), in chunks" },
      { id: "pepper", amount: "1–2, in strips" },
      { id: "onion", amount: "1 large, in wedges" },
      { id: "garlic", amount: "3 cloves, sliced" },
      { id: "tomato", amount: "350 g ripe (2 large or 3 medium), grated" },
      { id: "parsley", amount: "a handful" },
      { id: "oil", amount: "100 ml" },
      { id: "oregano", amount: "2 tsp dried" },
      { id: "salt", amount: "1 tsp, or to taste" },
      { id: "blackpepper", amount: "to taste" },
    ],
    method: [
      {
        text: "Cut all the vegetables into pieces of about the same size, the potatoes a little thinner.",
        why: "Roughly the same size so they cook in the same time — the potatoes thinner, because they are slowest.",
        prep: { potato: "in slices", courgette: "in rounds", aubergine: "in chunks", pepper: "in strips", onion: "in wedges", garlic: "sliced" },
      },
      {
        text: "Toss them in a large tin with the grated tomato, parsley, oregano, oil, salt and pepper, and spread them out in one loose layer.",
        why: "The oil is the point: the vegetables cook in it rather than in water. Spread out, not piled up, so they can brown later instead of stewing.",
        prep: { tomato: "grated", parsley: "chopped" },
        add: ["potato", "courgette", "aubergine", "pepper", "onion", "garlic", "tomato", "parsley", "oregano", "oil", "salt", "blackpepper"],
        sauce: "#d0643a",
      },
      {
        text: "Cover the tin with foil and bake at 190 °C until the potatoes are nearly soft.",
        why: "Under the foil the vegetables cook in the juice the courgettes and tomato let go, so no water is needed.",
        heat: "oven",
        wait: "45 min",
        sauce: "#cc5c34",
      },
      {
        text: "Take off the foil, stir once, gently, and bake uncovered until the liquid has gone and the edges are browned.",
        why: "Briam is done when the liquid has gone and the vegetables start to fry in the oil left behind. If the tin dries before the potatoes are soft, add a splash of water.",
        heat: "oven",
        wait: "40–45 min",
        sauce: "#b84a26",
      },
    ],
    serve: "Rested a little, warm or at room temperature — better still the next day — with bread and feta.",
    table: {
      dairy: "Dairy-free in the tin; feta on the side.",
      gluten: "Gluten-free in the tin; mind the bread.",
    },
  },
  {
    id: "lemonates",
    name: "Lemon potatoes",
    native: "Πατάτες λεμονάτες",
    line: "Potatoes roasted in lemon, olive oil, garlic and oregano until soft inside and golden at the edges.",
    story: "Usually the side dish to a Sunday roast chicken, and frequently the part everyone actually fights over.",
    serves: "4",
    time: "About 1¼ hours",
    fasting: true,
    vessel: "tin",
    key: ["potato", "lemon", "oregano", "oil", "garlic"],
    ingredients: [
      { id: "potato", amount: "1 kg, peeled, in thick wedges" },
      { id: "lemon", amount: "1½, juiced (about 60 ml)" },
      { id: "oil", amount: "70 ml" },
      { id: "garlic", amount: "2 cloves, crushed" },
      { id: "oregano", amount: "2 tsp dried" },
      { id: "salt", amount: "1½ tsp" },
      { id: "blackpepper", amount: "to taste" },
    ],
    method: [
      {
        text: "Toss the potatoes in a roasting tin with the lemon juice, oil, garlic, oregano, salt and pepper, and spread them out in one layer.",
        why: "Everything coats the potatoes before they go in, so every wedge carries the lemon and herb. One layer, because piled potatoes steam instead of browning.",
        prep: { potato: "in wedges", lemon: "juiced", garlic: "crushed" },
        add: ["potato", "lemon", "oil", "garlic", "oregano", "salt", "blackpepper"],
        sauce: "#efd98a",
      },
      {
        text: "Pour about 150 ml of water around the potatoes, so the liquid only comes a little way up them.",
        why: "The potatoes drink the lemony liquid as they cook, which is what makes them creamy inside rather than just roasted. More water gives softer, saucier potatoes; less, crisper ones. Many Greek cooks now whisk a spoon of mustard into the lemon, which thickens the juices.",
        sauce: "#ecd48a",
      },
      {
        text: "Roast uncovered at 200 °C (180 °C fan), turning once halfway, until the liquid is gone and the edges are golden.",
        why: "First they braise, then once the liquid has gone they fry in the oil left behind. Add a splash of water if the tin dries out before they are tender.",
        heat: "oven",
        wait: "1–1¼ hours",
        sauce: "#e7c46a",
      },
    ],
    serve: "Beside roast chicken or lamb — or on their own with a salad.",
    table: {
      dairy: "Dairy-free as written. Some older recipes dot butter or margarine over the top; olive oil alone is the usual way.",
      gluten: "Gluten-free as written. If you use stock instead of water, check it: stock cubes often hide wheat. Skip the semolina some cooks sprinkle on for crunch — it is wheat.",
    },
  },

  /* ================================================================= meat */
  {
    id: "stifado",
    name: "Stifado",
    native: "Στιφάδο",
    line: "Beef braised with whole small onions, red wine, vinegar and cinnamon.",
    story: "A Sunday dish, though not an expensive one: cheap meat, a mountain of onions — about as much onion as meat — and a long, slow afternoon. It is just as often made with rabbit, and by the sea with octopus.",
    serves: "4 to 6",
    time: "About 2½ hours, most of it hands-off",
    fasting: false,
    vessel: "pot",
    key: ["beef", "pearl", "wine", "vinegar", "cinnamon", "allspice"],
    ingredients: [
      { id: "beef", amount: "1 kg chuck or shin, in large pieces" },
      { id: "pearl", amount: "1 kg small onions or shallots, peeled" },
      { id: "oil", amount: "75 ml" },
      { id: "garlic", amount: "3 cloves, sliced" },
      { id: "paste", amount: "1 tbsp" },
      { id: "tomato", amount: "3 ripe, grated — or a 400 g tin" },
      { id: "wine", amount: "200 ml dry red" },
      { id: "vinegar", amount: "2 tbsp (30 ml) red wine vinegar" },
      { id: "sugar", amount: "1 tsp" },
      { id: "cinnamon", amount: "1 stick" },
      { id: "allspice", amount: "4 berries" },
      { id: "cloves", amount: "2 (optional)" },
      { id: "bay", amount: "2 leaves" },
      { id: "salt", amount: "to taste" },
      { id: "blackpepper", amount: "to taste" },
    ],
    method: [
      {
        text: "Blanch the small onions for a minute, cool them, trim the root end without cutting it off, and slip off the skins.",
        why: "The root end holds each onion together through the simmering.",
        prep: { pearl: "blanched and peeled" },
      },
      {
        text: "Pat the meat dry and brown it in half the oil, in batches, until deep brown on every side. Lift it out.",
        why: "Browning is where the flavour of the sauce comes from. Crowd the pot and the meat steams grey in its own juice instead. It needs no flour.",
        prep: { beef: "in large pieces, patted dry" },
        heat: 3,
        wait: "15 min",
      },
      {
        text: "Brown the onions whole in the rest of the oil until golden in patches, and lift them out too. Lower the heat, then stir in the garlic, spices and tomato paste until the paste darkens.",
        why: "Spices warmed in fat release aromas water cannot carry, and fried paste loses its raw edge. Both burn quickly, which is why the heat comes down first.",
        prep: { garlic: "sliced" },
        add: ["oil", "garlic", "cinnamon", "allspice", "cloves", "bay", "paste"],
        heat: 1,
        wait: "2 min",
        sauce: "#9a3322",
      },
      {
        text: "Pour in the wine and vinegar and scrape the bottom. Let it bubble for two minutes.",
        why: "The brown film on the bottom is concentrated flavour; the wine dissolves it into the sauce. The bubbling drives off the sharpest of the alcohol and the vinegar.",
        add: ["wine", "vinegar"],
        heat: 3,
        wait: "2 min",
        sauce: "#6a2420",
      },
      {
        text: "Return the meat with the tomatoes, the sugar and enough water to just cover — about 500 ml. Salt lightly, cover, and keep at the gentlest simmer.",
        why: "A lazy bubble melts the meat's collagen and keeps it juicy; a hard boil squeezes the fibres dry. The spoon of sugar rounds off the vinegar rather than sweetening. Salt lightly because the sauce will reduce.",
        prep: { tomato: "grated" },
        add: ["beef", "tomato", "sugar", "salt"],
        heat: 1,
        wait: "1¼ hours",
        sauce: "#842c1f",
      },
      {
        text: "Nestle in the onions and simmer another 45 minutes, shaking the pot rather than stirring, until the beef yields to a fork and the sauce is thick. Uncover for the last minutes if it is thin. Taste, then fish out the cinnamon and bay.",
        why: "Added for the last stretch the onions soften but stay whole, and a spoon would break them. At the end, salt if it tastes flat, a few more minutes uncovered if it tastes thin.",
        add: ["pearl", "blackpepper"],
        heat: 1,
        wait: "45 min",
        sauce: "#7a2a1e",
      },
    ],
    serve: "With fried or boiled potatoes, rice, or bread for the sauce.",
    table: {
      gluten: "Gluten-free in the pot, as long as nobody dusts the meat in flour (a few recipes do; it does not need it) or reaches for a stock cube (water is what most cooks use, and cubes often hide wheat). Serve it with potatoes or rice rather than bread or pasta.",
    },
  },

  /* ========================================================== meze, cold */
  {
    id: "horiatiki",
    name: "Horiatiki",
    native: "Χωριάτικη σαλάτα",
    line: "The village salad: tomato, cucumber, onion, pepper and olives, with oregano, olive oil and a slab of feta.",
    story: "No lettuce, ever. Made only in summer when the tomatoes are worth eating raw, and served with the oil and juices pooling at the bottom of the bowl — which is what the bread is for. Islands add capers, Crete puts it on a barley rusk, and every family argues about the vinegar.",
    serves: "4",
    time: "15 minutes",
    fasting: false,
    vessel: "bowl",
    key: ["tomato", "cucumber", "redonion", "olives", "oregano"],
    ingredients: [
      { id: "tomato", amount: "3–4 ripe (about 500 g), in wedges" },
      { id: "cucumber", amount: "1, peeled or in stripes, in thick half-moons" },
      { id: "redonion", amount: "½, in thin rings" },
      { id: "pepper", amount: "1 green, in rings" },
      { id: "olives", amount: "about 12 Kalamata" },
      { id: "capers", amount: "1–2 tbsp (optional)" },
      { id: "feta", amount: "a 150 g slab — traditionally" },
      { id: "oregano", amount: "1½ tsp dried" },
      { id: "vinegar", amount: "1–1½ tbsp red wine" },
      { id: "oil", amount: "4 tbsp, good" },
      { id: "salt", amount: "a pinch" },
    ],
    method: [
      {
        text: "Cut the tomatoes in wedges, the cucumber in thick half-moons — peeled, or in stripes — and the onion and pepper in thin rings.",
        why: "Big, rough pieces: this is a salad you eat with a fork and bread, not a chopped salsa. Striping the cucumber keeps some crunch and colour without the bitter skin.",
        prep: { tomato: "in wedges", cucumber: "in half-moons", redonion: "in thin rings", pepper: "in rings" },
      },
      {
        text: "Put them in a wide bowl with the olives and capers. Salt, sprinkle with the vinegar and oil, and toss gently.",
        why: "Salt draws the juice from the tomatoes, and that juice with the oil is most of the dressing. The vinegar is only a splash to sharpen it; some cooks leave it out altogether.",
        add: ["tomato", "cucumber", "redonion", "pepper", "olives", "capers", "salt", "vinegar", "oil"],
        sauce: "#f0e6cf",
      },
      {
        text: "Lay the feta on top in one slab, if it is being eaten, and crumble the oregano over everything between your fingers.",
        why: "Crushing dried oregano wakes its oils. The feta stays whole so each person breaks off what they want — and it can just as well sit on its own plate.",
        add: ["feta", "oregano"],
        sauce: "#f0e6cf",
      },
    ],
    serve: "At once, with bread for the juices.",
    table: {
      dairy: "Leave the slab of feta off, or serve it on its own plate. With good tomatoes and plenty of oil and oregano, nothing is missing.",
      gluten: "Gluten-free in the bowl. The bread for the juices is the thing to watch — and the Cretan way, on a barley rusk, is not gluten-free either.",
    },
  },
  {
    id: "fava",
    name: "Fava",
    native: "Φάβα",
    line: "A golden purée of yellow split peas, with raw onion, capers and olive oil on top.",
    story: "On Santorini it is made from a grass pea grown in the island's volcanic soil and is protected by name; everywhere else, yellow split peas. A Lenten standby in every Greek house, served smooth as velvet with everything sharp piled on top, and lemon on the side for whoever wants it.",
    serves: "4",
    time: "About 1 hour",
    fasting: true,
    vessel: "pot",
    key: ["splitpeas", "onion", "capers", "lemon", "oil"],
    ingredients: [
      { id: "splitpeas", amount: "250 g, rinsed" },
      { id: "onion", amount: "1, chopped" },
      { id: "oil", amount: "100 ml: half in the pot, half to finish" },
      { id: "salt", amount: "about ¾ tsp" },
      { id: "bay", amount: "1 leaf (optional)" },
      { id: "lemon", amount: "1: half juiced, half in wedges" },
      { id: "redonion", amount: "½, finely chopped, to top" },
      { id: "capers", amount: "1 tbsp, to top" },
    ],
    method: [
      {
        text: "Rinse the split peas well, until the water runs clear.",
        why: "Split peas need no soaking; rinsing takes away the dusty starch that would foam over.",
        prep: { splitpeas: "rinsed" },
      },
      {
        text: "Soften the onion in half the oil, then add the split peas, the bay if using, the salt and about 750 ml of water. Bring to the boil and skim off the foam.",
        why: "Three parts water to one of peas is the usual ratio. The foam is starch; skim it, and leave the lid off at first, or it boils over.",
        prep: { onion: "chopped" },
        add: ["oil", "onion", "splitpeas", "bay", "salt"],
        heat: 2,
        wait: "5 min",
        sauce: "#e8c65a",
      },
      {
        text: "Turn it down and simmer gently, half-covered, until the peas have collapsed into a thick porridge. Stir now and then near the end, adding a splash of hot water if it catches before the peas are soft.",
        why: "They should fall apart completely. Early on, leave them alone; near the end the purée thickens and wants to stick.",
        heat: 1,
        wait: "45–60 min",
        sauce: "#ecc24a",
      },
      {
        text: "Take out the bay and blend until smooth, stirring in the juice of half the lemon. Taste for salt. It thickens as it cools.",
        why: "Fava sets like mash once cold, so leave it looser than you want to eat it. Many Greek cooks keep the lemon out of the pot altogether and squeeze it at the table.",
        prep: { lemon: "half juiced, half in wedges" },
        add: ["lemon"],
        heat: 0,
        sauce: "#f0cc58",
      },
      {
        text: "Spread on a plate, pour over the rest of the oil and scatter with raw onion and capers. Put the lemon wedges alongside.",
        why: "Sweet, smooth purée against sharp raw onion and salty capers is the whole dish.",
        prep: { redonion: "finely chopped", capers: "rinsed" },
        add: ["oil", "redonion", "capers"],
        sauce: "#f0cc58",
      },
    ],
    serve: "Warm or at room temperature, as a meze with bread.",
    table: {
      gluten: "Gluten-free on the plate; it is usually scooped up with bread, so offer something else to dip. Some cooks simmer it in stock — a cube can hide wheat, and water is all it needs.",
    },
  },
  {
    id: "melitzanosalata",
    name: "Melitzanosalata",
    native: "Μελιτζανοσαλάτα",
    line: "Smoky aubergine dip with garlic, vinegar, parsley and olive oil.",
    story: "The aubergines are burnt whole over a flame until they collapse, which gives the dip its smoke; in a city flat, a hot oven and a grill do most of the job. Every meze table has one, and every cook guards their own proportions — the plain one here, with no cheese and no mayonnaise, is the one most Greek cooks make in the fasting weeks and the rest of the year too.",
    serves: "4 as a meze",
    time: "About 1 hour, plus 30 minutes to chill",
    fasting: true,
    vessel: "bowl",
    key: ["aubergine", "garlic", "vinegar", "parsley"],
    ingredients: [
      { id: "aubergine", amount: "2 large (about 1 kg)" },
      { id: "garlic", amount: "1–2 cloves, crushed" },
      { id: "vinegar", amount: "2 tbsp" },
      { id: "oil", amount: "60 ml, plus a little to finish" },
      { id: "parsley", amount: "2 tbsp, chopped" },
      { id: "lemon", amount: "a squeeze (optional)" },
      { id: "redonion", amount: "¼, very finely chopped (optional)" },
      { id: "salt", amount: "about 1 tsp" },
      { id: "blackpepper", amount: "to taste" },
    ],
    method: [
      {
        text: "Prick the aubergines a few times and char them whole over a gas flame or on a barbecue, turning, until the skin is black and they collapse. Without a flame, roast them at 220 °C and finish under a hot grill.",
        why: "Pricking stops them bursting. The burnt skin is what flavours the flesh with smoke; the oven alone gives a milder, sweeter dip, which is why the grill goes on at the end.",
        prep: { aubergine: "pricked and charred" },
        heat: 3,
        wait: "20–25 min on a flame, 45–60 in the oven",
      },
      {
        text: "While they are hot, split them and scoop the flesh into a colander, leaving the skin behind. Let it drain, pressing now and then.",
        why: "The juice that runs out is bitter and watery; a dip made without draining is thin and sharp. Scoop quickly and the flesh stays pale — a squeeze of lemon over it helps.",
        prep: { aubergine: "scooped out" },
        wait: "15–30 min",
      },
      {
        text: "Chop the drained flesh finely with a knife and put it in a bowl.",
        why: "A knife, not a blender, keeps some texture — a blended one turns gluey and stops being melitzanosalata.",
        prep: { aubergine: "finely chopped" },
        add: ["aubergine"],
        sauce: "#bfa98a",
      },
      {
        text: "Stir in the garlic, vinegar, parsley, salt and pepper, and the onion and lemon if using, then stir in the oil. Taste, and chill before serving with a little more oil on top.",
        why: "Vinegar is the main sharpness; lemon is a second, lighter note some cooks add. A rest in the fridge lets the raw garlic soften into the aubergine.",
        prep: { garlic: "crushed", parsley: "chopped", redonion: "very finely chopped", lemon: "juiced" },
        add: ["garlic", "vinegar", "parsley", "salt", "blackpepper", "redonion", "lemon", "oil"],
        heat: 0,
        wait: "30 min to chill",
        sauce: "#c9b494",
      },
    ],
    serve: "Cool, as a meze, with bread or raw vegetables.",
    table: {
      dairy: "Some versions, mostly taverna ones, stir in feta, yogurt or mayonnaise (which also brings egg). This one has none.",
      gluten: "Gluten-free in the bowl, as long as nobody thickens it with breadcrumbs, as a few cooks do. Dip raw cucumber and pepper instead of bread.",
    },
  },
  {
    id: "skordalia",
    name: "Skordalia",
    native: "Σκορδαλιά",
    line: "A thick, fierce garlic and potato dip, sharpened with vinegar.",
    story: "The traditional partner of fried salt cod on the 25th of March, and of beetroot and fried courgettes all year. Made with potato, as here; in the north with walnuts and bread, and on the Ionian islands loosened with the fish's own broth. Every version but the potato one has bread in it, which is not gluten-free.",
    serves: "4 as a meze",
    time: "About 40 minutes",
    fasting: true,
    vessel: "bowl",
    key: ["potato", "garlic", "vinegar", "oil"],
    ingredients: [
      { id: "potato", amount: "500 g floury" },
      { id: "garlic", amount: "3 cloves, or more to taste" },
      { id: "vinegar", amount: "1½ tbsp" },
      { id: "oil", amount: "100 ml" },
      { id: "salt", amount: "about 1 tsp" },
      { id: "lemon", amount: "a squeeze (optional)" },
    ],
    method: [
      {
        text: "Peel the potatoes, cut them in chunks and boil in salted water until soft. Drain, keeping a cupful of the water, and let them steam dry in the pot for a few minutes.",
        why: "Chunks cook in twenty minutes. Steaming off the water keeps them fluffy; wet potato makes a gummy, sloppy dip.",
        prep: { potato: "peeled and cut in chunks" },
        heat: 2,
        wait: "20 min",
      },
      {
        text: "Meanwhile, pound the garlic to a paste with the salt in a mortar — or blitz it with a spoonful of the oil and the vinegar.",
        why: "Garlic can go through a machine; potato cannot. The salt grinds it and tames its raw edge.",
        prep: { garlic: "pounded with salt" },
      },
      {
        text: "While the potatoes are still warm, mash them by hand with the garlic paste.",
        why: "Warm potato takes up the garlic and oil smoothly; cold, it goes lumpy. Mash or rice by hand, never blend: potato worked in a blender turns to glue.",
        add: ["potato", "garlic", "salt"],
        sauce: "#f1e6c6",
      },
      {
        text: "Beat in the oil and vinegar in a few goes, with a squeeze of lemon if you like, loosening with a spoonful or two of the potato water until thick and smooth. Taste.",
        why: "A few additions are enough — the potato holds the oil, so it need not go in drop by drop as for mayonnaise. Skordalia should be properly fierce, and it gets fiercer as it sits.",
        prep: { lemon: "juiced" },
        add: ["oil", "vinegar", "lemon"],
        sauce: "#f3eacb",
      },
    ],
    serve: "At room temperature, with fried fish, beetroot or fried vegetables.",
    table: {
      gluten: "Made with potato, it is gluten-free. The bread version, made from soaked stale bread, is not — ask which one you are being served.",
      egg: "A few cooks beat in an egg for body. This one has none, and does not need it.",
    },
  },
];

/** The dishes in `recipes` an ingredient goes into, for its card. */
export function dishesWith(recipes, id) {
  return recipes.filter((r) => r.ingredients.some((i) => i.id === id));
}

/**
 * What the counter could become: every dish with at least one of its key
 * ingredients on the counter, best first. `have` and `missing` are key ids.
 */
export function suggest(recipes, counter) {
  const out = [];
  for (const r of recipes) {
    const have = r.key.filter((id) => counter.has(id));
    if (!have.length) continue;
    out.push({ recipe: r, have, missing: r.key.filter((id) => !counter.has(id)) });
  }
  return out.sort(
    (a, b) => b.have.length / b.recipe.key.length - a.have.length / a.recipe.key.length || a.missing.length - b.missing.length,
  );
}

/** What a dish contains for this table, from its ingredients. */
export function containsOf(recipe, byId) {
  return [...new Set(recipe.ingredients.flatMap((i) => byId[i.id].contains || []))];
}

export const FASTING_NOTE =
  "A fasting dish. On Orthodox fasting days — more than half the year for the devout — the traditional table goes without meat, dairy and eggs, which is why so much of Greek cooking is dairy-free and egg-free by design.";
