/*
 * sources.js — where every researched recipe came from. GENERATED by
 * tools/build-sources.mjs from research/<kitchen>/<dish>.md; do not edit by
 * hand, edit the research file and re-run the script.
 */
export const SOURCES = {
  "greek": {
    "avgolemono": {
      "researched": "2026-10-04",
      "sources": [
        {
          "name": "Cookout (SKAI), \"Κλασική κοτόσουπα αυγολέμονο βήμα-βήμα\"",
          "url": "https://cookout.skai.gr/recipes/kotosoupa-aygolemono",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Argiro Barbarigou",
          "url": "https://www.argiro.gr/en/recipe/chicken-soup-with-egg-lemon-sauce-avgolemono/",
          "lang": "el/en",
          "weight": 2
        },
        {
          "name": "paxxi.gr, \"της γιαγιάς\" (grandmother's)",
          "url": "https://paxxi.gr/syntages/kotosoupa-augolemono-ths-giagias/",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Syntages tis mamas (sintagesmamas.com)",
          "url": "https://www.sintagesmamas.com/kotosoupa-augolemono",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Nikolopaa",
          "url": "https://nikolopaa.com/kotosoupa-avgolemono-greek-chicken-lemon-soup/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Mary's Kouzina (Mary Politis)",
          "url": "https://www.maryskouzina.com/kotosoupa-avgolemono-greek-chicken-and-egg-lemon-soup/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "The Cookbook Kitchen (HK)",
          "url": "https://www.thecookbookkitchen.com.au/recipes/kotosoupa",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "My Prep Table (chef Nikolaos Saragias)",
          "url": "https://www.mypreptable.com/kotosoupa-greek-chicken-soup/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "live-kitchen.gr",
          "url": "https://live-kitchen.gr/kotosoupa-avgolemono/",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Dimitra's Dishes",
          "url": "https://www.dimitrasdishes.com/greek-chicken-avgolemono-soup-lemony-chicken-and-orzo-soup/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Online Culinary School (Chef Eric)",
          "url": "https://onlineculinaryschool.net/chicken-soup-kotosoupa-avgolemono-video-recipe/",
          "lang": "en",
          "weight": 0.5
        },
        {
          "name": "Maria Siam (Cookpad), via HealthStat.gr",
          "url": "https://www.healthstat.gr/ev-zin/45469/syntagi-gia-kotosoupa-avgolemono-ola-ta-mystika-gia-na-vgainei-panta-veloydini",
          "lang": "el",
          "weight": 0.5
        },
        {
          "name": "Diane Kochilas, adapted by Saveur",
          "url": "https://www.saveur.com/article/recipes/avgolemono/",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "iCookToHeal (Dr Filitsa Sougioultzoglou)",
          "url": "https://icooktoheal.com/greek-chicken-soup-kotosoupa-avgolemono/",
          "lang": "en",
          "weight": 1
        }
      ]
    },
    "briam": {
      "researched": "2026-10-04",
      "sources": [
        {
          "name": "Argiro Barbarigou",
          "url": "https://www.argiro.gr/en/recipe/briam-greek-roasted-summer-vegetables/",
          "lang": "EN (Greek site)",
          "weight": 2
        },
        {
          "name": "Petros Syrigos",
          "url": "https://petros-syrigos.com/mpriam/",
          "lang": "GR",
          "weight": 2
        },
        {
          "name": "Elena Paravantes, Olive Tomato",
          "url": "https://www.olivetomato.com/briami-the-greek-ratatouille/",
          "lang": "EN",
          "weight": 2
        },
        {
          "name": "iefimerida.gr",
          "url": "https://www.iefimerida.gr/gastronomie/mpriam-sto-foyrno-syntagi-gia-kalokairino-trapezi",
          "lang": "GR",
          "weight": 0.5
        },
        {
          "name": "Souvlaki For The Soul",
          "url": "https://souvlakiforthesoul.com/briam-greek-roasted-vegetables/",
          "lang": "EN",
          "weight": 1
        },
        {
          "name": "Mama Peinao",
          "url": "https://www.mamapeinao.gr/mpriam/",
          "lang": "GR",
          "weight": 1
        },
        {
          "name": "Cretan Gastronomy",
          "url": "https://www.cretangastronomy.gr/2014/09/briam-fournou/",
          "lang": "GR",
          "weight": 2
        },
        {
          "name": "Mamazilla Food",
          "url": "https://www.mamazillafood.com/briam-laxanika-sto-fourno/",
          "lang": "GR",
          "weight": 1
        },
        {
          "name": "Anna Chalikia",
          "url": "https://www.annachalikia.com/blog/mpriam",
          "lang": "GR",
          "weight": 2
        },
        {
          "name": "Marilena's Kitchen",
          "url": "https://marilenaskitchen.com/greek-summer-roasted-vegetables-briami/",
          "lang": "EN",
          "weight": 2
        },
        {
          "name": "Cantina (protothema.gr)",
          "url": "https://cantina.protothema.gr/recipe/briam-sto-fourno-me-myrodika/",
          "lang": "GR",
          "weight": 1
        },
        {
          "name": "Platings & Pairings",
          "url": "https://www.platingsandpairings.com/briam-recipe/",
          "lang": "EN",
          "weight": 1
        },
        {
          "name": "My Greek Dish",
          "url": "https://www.mygreekdish.com/recipe/briam-recipe-greek-mixed-roasted-vegetables/",
          "lang": "EN",
          "weight": 1
        },
        {
          "name": "Diane Kochilas",
          "url": "https://www.dianekochilas.com/briam-baked-summer-vegetable-casserole/",
          "lang": "EN",
          "weight": 2
        },
        {
          "name": "Dimitra's Dishes",
          "url": "https://www.dimitrasdishes.com/easy-briam-roasted-veggies/",
          "lang": "EN",
          "weight": 2
        },
        {
          "name": "Akis Petretzikis (\"Παραδοσιακό μπριάμ\")",
          "url": "https://akispetretzikis.com/recipe/5786/paradosiako-mpriam",
          "lang": "GR",
          "weight": 2
        }
      ]
    },
    "fakes": {
      "researched": "2026-10-04",
      "sources": [
        {
          "name": "My Greek Dish",
          "url": "https://www.mygreekdish.com/recipe/lentil-soup-fakes-soupa/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Diane Kochilas",
          "url": "https://www.dianekochilas.com/greek-lentil-soup-fakes/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Dimitra's Dishes",
          "url": "https://www.dimitrasdishes.com/greek-lentil-soup-fakes/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Mia Kouppa",
          "url": "https://miakouppa.com/fakies-lentil-soup/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Ioanna Stamoulou, Cookout (SKAI)",
          "url": "https://cookout.skai.gr/recipes/fakes-soupa",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Greek Cooking by Katerina",
          "url": "https://www.greekcookingbykaterina.com/recipes/recipe/24/fakes-soupa",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Mamazilla",
          "url": "https://www.mamazillafood.com/paradosiakes-fakes-soupa/",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Souvlaki for the Soul (Peter G)",
          "url": "https://souvlakiforthesoul.com/2010/03/lentil-soup-fakes",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Eleni Saltas",
          "url": "https://elenisaltas.com/2018/02/20/fakes-greek-lentil-soup/",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "SBS Food, \"Why I love fakes\"",
          "url": "https://www.sbs.com.au/food/article/why-i-love-fakes-the-powerhouse-greek-lentil-soup/60zwfg393",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Cantina (Proto Thema), with balsamic",
          "url": "https://cantina.protothema.gr/recipe/fakes-soupa-3/",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Greek City Times",
          "url": "https://greekcitytimes.com/2017/08/09/fakes-greek-lentil-soup-recipe/",
          "lang": "en",
          "weight": 0.5
        },
        {
          "name": "Argiro Barbarigou",
          "url": "https://www.argiro.gr/en/recipe/argiros-lentil-soup/",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Xrysoskoufaki",
          "url": "https://xrysoskoufaki.gr/%CF%86%CE%B1%CE%BA%CE%AD%CF%82-%CF%80%CE%B1%CF%81%CE%B1%CE%B4%CE%BF%CF%83%CE%B9%CE%B1%CE%BA%CE%AD%CF%82/",
          "lang": "el",
          "weight": 2
        }
      ]
    },
    "fasolada": {
      "researched": "2026-10-04",
      "sources": [
        {
          "name": "My Greek Dish",
          "url": "https://www.mygreekdish.com/recipe/traditional-greek-bean-soup-recipe-fasolada/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Argiro Barbarigou",
          "url": "https://www.argiro.gr/en/recipe/creamy-white-bean-soup/",
          "lang": "el/en",
          "weight": 2
        },
        {
          "name": "Yiannis Lucacos",
          "url": "https://www.yiannislucacos.gr/recipe/ellinika-spitika-hortofagikes-ospria-lahanika/7481/fasolada",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Cantina (Proto Thema)",
          "url": "https://cantina.protothema.gr/recipe/fasolada-i-paradosiaki/",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Mia Kouppa",
          "url": "https://miakouppa.com/fasolatha-%CF%86%CE%B1%CF%83%CE%BF%CE%BB%CE%AC%CE%B4%CE%B1/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Foodathlon",
          "url": "https://foodathlon.com/traditional-greek-bean-soup-fasolada/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Diane Kochilas, Classic Greek Bean Soup (plus her \"Template\" page)",
          "url": "https://www.dianekochilas.com/classic-greek-bean-soup-fasolada-2/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Dimitra's Dishes",
          "url": "https://www.dimitrasdishes.com/fasolada/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Greek Cooking by Katerina",
          "url": "https://www.greekcookingbykaterina.com/recipes/recipe/31/fasolada",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Zoi Papafotiou, via iefimerida.gr",
          "url": "https://www.iefimerida.gr/gastronomie/syntagi-gia-paradosiaki-fasolada-mystiko",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "sintayes.gr",
          "url": "https://www.sintayes.gr/syntages/fasolada-kokkinisti/",
          "lang": "el",
          "weight": 0.5
        },
        {
          "name": "Olive & Mango (Joanne Rappos)",
          "url": "https://www.oliveandmango.com/greek-white-bean-soup-fasolada/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Marilena's Kitchen",
          "url": "https://marilenaskitchen.com/traditional-greek-bean-soup/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Katerina's Kouzina (Poros)",
          "url": "https://katerinaskouzina.com/vegetarian/fasolada-bean-soup.html",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Well Seasoned Studio (Ari Laing)",
          "url": "https://www.wellseasonedstudio.com/greek-white-bean-soup/",
          "lang": "en",
          "weight": 1
        }
      ]
    },
    "fasolakia": {
      "researched": "2026-10-04",
      "sources": [
        {
          "name": "Ioanna Stamoulou, Cantina",
          "url": "https://cantina.protothema.gr/recipe/fasolakia-ladera/",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Giorgos Tsoulis",
          "url": "https://giorgostsoulis.com/syntages/ospria-ladera/fasolakia",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "nefroiatriki.gr",
          "url": "https://nefroiatriki.gr/syntages/fasolakia-ladera-me-patates/",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "kritikes-geuseis.gr, \"Fasoulopatates\"",
          "url": "https://kritikes-geuseis.gr",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Argiro Glyka (Cookpad)",
          "url": "https://cookpad.com/gr/sintages/15637029",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Argiro Barbarigou",
          "url": "https://argiro.gr/en/recipe/green-beans-in-olive-oil/",
          "lang": "el/en",
          "weight": 2
        },
        {
          "name": "Zoi Papafotiou, iefimerida",
          "url": "https://iefimerida.gr/gastronomie/syntagi-gia-teleia-fasolakia-ladera",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Dimitris Papazymouris",
          "url": "https://caruso.gr/ladera-fasolakia/",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Vasilis Natsios, cosmopoliti.com",
          "url": "https://cosmopoliti.com",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Efthymis, The Hungry Bites",
          "url": "https://gr.thehungrybites.com/fasolakia-ladera/",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Mia Kouppa (Bitzas sisters)",
          "url": "https://miakouppa.com",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Diane Kochilas",
          "url": "https://dianekochilas.com/fasolakia-yiahni-green-beans-in-tomato-sauce/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Dimitra Alfas, Dimitra's Dishes",
          "url": "https://dimitrasdishes.com/fasolakia-braised-green-beans/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Elena Paravantes, OliveTomato",
          "url": "https://olivetomato.com/greek-style-green-beans-fasolakia-lathera/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Fotini, Real Greek Recipes",
          "url": "https://realgreekrecipes.com/greek-green-beans/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "My Greek Dish",
          "url": "https://mygreekdish.com/recipe/greek-green-beans-recipe-fasolakia-giaxni/",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "GCT Team, Greek City Times",
          "url": "https://greekcitytimes.com/2017/10/02/fasolakia-ladera-recipe/",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Carol Borchardt, From A Chef's Kitchen",
          "url": "https://fromachefskitchen.com/fasolakia/",
          "lang": "en",
          "weight": 1
        }
      ]
    },
    "fava": {
      "researched": "2026-10-04",
      "sources": [
        {
          "name": "Eirini Zevelaki, paxxi.gr",
          "url": "https://paxxi.gr/blog/paradosiaki-fava/",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Argiro Barbarigou, \"Fava of the Aegean\"",
          "url": "https://www.argiro.gr/en/recipe/fava-of-the-aegean/",
          "lang": "el (en page)",
          "weight": 2
        },
        {
          "name": "Yiannis Lucacos",
          "url": "https://www.yiannislucacos.gr/recipe/orektika/3160/fava-me-tiganiti-kappari-kai-karamelomeno-kremmydi",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Sitronella (Trachila), Cookpad",
          "url": "https://cookpad.com/gr/sintages/3066679",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "\"anna\", sidages.gr",
          "url": "https://www.sidages.gr/syntages/faba-santorinis",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Ilias Mamalakis, via zinapost.gr",
          "url": "https://www.zinapost.gr/well-being/224898_fava-me-karamelomena-kremmydia-kai-kapari-apo-ton-ilia-mamalaki/",
          "lang": "el",
          "weight": 0.5
        },
        {
          "name": "Akis Petretzikis, via eirinika.gr and Samsung Food",
          "url": "https://app.samsungfood.com/recipes/1019a480ee614077b9b5ad45f6007f01f337ede5786",
          "lang": "el",
          "weight": 0.5
        },
        {
          "name": "Diane Kochilas",
          "url": "https://www.dianekochilas.com/yellow-split-pea-puree-fava/",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Dimitra's Dishes",
          "url": "https://www.dimitrasdishes.com/fava-dip-greek-style-split-pea-dip/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Mia Kouppa",
          "url": "https://miakouppa.com/fasting-and-fava/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Eli K. Giannopoulos, My Greek Dish",
          "url": "https://www.mygreekdish.com/recipe/authentic-greek-fava-recipe-yellow-split-peas-puree/",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Fotini, Real Greek Recipes",
          "url": "https://realgreekrecipes.com/fava/",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "America's Test Kitchen",
          "url": "https://www.americastestkitchen.com/recipes/17528-fava-greek-yellow-split-pea-dip",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Efthimis Koukakis, The Hungry Bites",
          "url": "https://www.thehungrybites.com/yellow-split-pea-puree/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Joanne Rappos, Olive & Mango",
          "url": "https://www.oliveandmango.com/easy-greek-fava-recipe-yellow-spilt-pea-puree-dip/",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Mediterranean Living (Stamatis family, Ikaria)",
          "url": "https://www.mediterraneanliving.com/greek-fava/",
          "lang": "en",
          "weight": 0.5
        }
      ]
    },
    "gemista": {
      "researched": "2026-10-04",
      "sources": [
        {
          "name": "Giorgos Tsoulis",
          "url": "https://giorgostsoulis.com/syntages/ospria-ladera/gemista",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Argiro Barbarigou, \"Γεμιστά ορφανά\"",
          "url": "https://argiro.gr/recipe/gemista-orfana/",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Lilian Apostolopoulou, \"της γιαγιάς\" (Cookpad)",
          "url": "https://cookpad.com/gr/sintages/16336273",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Makos / Efthimis Koukakis, The Hungry Bites",
          "url": "https://thehungrybites.com/meatless-greek-stuffed-vegetables-gemista/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Katerina's Kouzina (Poros)",
          "url": "https://katerinaskouzina.com/vegetarian/gemista-stuffed-tomatoes-peppers.html",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Elleni Katalanos, The Green Greek",
          "url": "https://thegreengreekchef.com",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "alwayshungry.gr",
          "url": "https://alwayshungry.gr/syntagi-gia-gemista-paradosiaka/",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Diane Kochilas",
          "url": "https://dianekochilas.com/stuffed-tomatoes-peppers-gemista/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "My Greek Dish",
          "url": "https://mygreekdish.com/recipe/gemista-stuffed-tomatoes-peppers-and-onions/",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Elena Paravantes, OliveTomato",
          "url": "https://olivetomato.com",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "iefimerida.gr, \"ορφανά\"",
          "url": "https://iefimerida.gr/gastronomie/syntagi-gia-apaihta-gemista-orfana",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Petros Syrigos",
          "url": "https://petros-syrigos.com/gemista-orfana/",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Kitchen Queen",
          "url": "https://kitchenqueen.gr",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Fotini, Real Greek Recipes",
          "url": "https://realgreekrecipes.com/stuffed-vegetables/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Mia Kouppa",
          "url": "https://miakouppa.com/yemista-or-gemista/",
          "lang": "en",
          "weight": 2
        }
      ]
    },
    "gigantes": {
      "researched": "2026-10-04",
      "sources": [
        {
          "name": "Argiro Barbarigou",
          "url": "https://www.argiro.gr/recipe/gigantes-plaki-me-feta/",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Giannis Gavalas, LiFO",
          "url": "https://www.lifo.gr/recipes/gigantes-plaki",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Konstantina's Kitchen",
          "url": "https://www.konstantinas-kitchen.gr/fasolia-gigantes-sto-fourno-gigantes-plaki/",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "BBC Good Food (ME edition)",
          "url": "https://www.bbcgoodfoodme.com/recipes/gigantes-plaki/",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Mia Kouppa (Helen & Billie)",
          "url": "https://miakouppa.com/gigantes-plaki-%CF%86%CE%B1%CF%83%CF%8C%CE%BB%CE%B9%CE%B1-%CE%B3%CE%AF%CE%B3%CE%B1%CE%BD%CF%84%CE%B5%CF%82/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Lazy Cat Kitchen",
          "url": "https://www.lazycatkitchen.com/gigantes-plaki/",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Olive & Mango",
          "url": "https://www.oliveandmango.com/gigantes-plaki-greek-style-baked-white-beans/",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Katerina's Kouzina",
          "url": "https://katerinaskouzina.com/vegetarian/gigantes-plaki-baked-broad-beans.html",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Sia's cooking",
          "url": "https://siaiscooking.com/fasolia-gigantes-sto-fourno-syntagi/",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Athinorama Tasty",
          "url": "https://tasty.athinorama.gr/suntages/almires-syntages/701255/gigantes-plaki/",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Akis Petretzikis",
          "url": "https://akispetretzikis.com/recipe/3442/gigantes-foyrnoy",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Diane Kochilas",
          "url": "https://www.dianekochilas.com/best-gigantes-recipe-greek-giant-beans-casserole/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "My Greek Dish (Eli Giannopoulos)",
          "url": "https://www.mygreekdish.com/recipe/gigantes-plaki-greek-baked-giant-beans/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Dimitra's Dishes",
          "url": "https://www.dimitrasdishes.com/gigantes-baked-giant-bean-casserole/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "sintayes.gr",
          "url": "https://www.sintayes.gr/syntages/gigantes-plaki-sto-fourno/",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "iCookGreek",
          "url": "https://www.icookgreek.com/syntagi/gigantes-plaki/",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Cantina (protothema)",
          "url": "https://cantina.protothema.gr/recipe/gigantes-plaki-me-feta/",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Kopiaste (Ivy Liacopoulou)",
          "url": "https://www.kopiaste.org/2010/03/gigantes-plaki-sto-fourno-baked-giant-beans/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Agrino",
          "url": "https://www.agrino.gr/syntages/syntages-me-ospria/fasolia-gigantes-plaki",
          "lang": "el",
          "weight": 0.5
        },
        {
          "name": "Greek City Times (Bill Giannopoulos)",
          "url": "https://greekcitytimes.com/2020/11/29/traditional-gigantes-plaki-recipe-2/",
          "lang": "en",
          "weight": 1
        }
      ]
    },
    "horiatiki": {
      "researched": "2026-10-04",
      "sources": [
        {
          "name": "Argiro Barbarigou",
          "url": "https://www.argiro.gr/en/recipe/horiatiki-salad/",
          "lang": "el (en page)",
          "weight": 1
        },
        {
          "name": "Karolina Doriti, Cookout (SKAI)",
          "url": "https://cookout.skai.gr/recipes/xoriatiki-salata",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Akis Petretzikis",
          "url": "https://akispetretzikis.com/recipe/1971/chwriatikh-salata",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Ivy Liacopoulou, Kopiaste",
          "url": "https://kopiaste.info/2007/10/choriatiki-salata-elliniki/",
          "lang": "el/en",
          "weight": 2
        },
        {
          "name": "Julia, Mamazilla",
          "url": "https://mamazillafood.com/xwriatiki-salata/",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Geo, Cookpad GR",
          "url": "https://cookpad.com/gr/sintages/24447432",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Greek Flavours (shop blog)",
          "url": "https://greekflavours.com/el/blogs/syntages/paradosiaki-choriatiki-salata",
          "lang": "el",
          "weight": 0.5
        },
        {
          "name": "Dimitra's Dishes",
          "url": "https://www.dimitrasdishes.com/3-greek-summer-salads-without-lettuce/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Eli K. Giannopoulos, My Greek Dish",
          "url": "https://www.mygreekdish.com/recipe/greek-feta-salad/",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Fotini, Real Greek Recipes",
          "url": "https://realgreekrecipes.com/classic-greek-salad-recipe/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Mia Kouppa",
          "url": "https://miakouppa.com/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Joanne Rappos, Olive & Mango",
          "url": "https://www.oliveandmango.com/classic-greek-village-salad-horiatiki/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Eleni Saltas",
          "url": "https://elenisaltas.com/2017/08/03/horiatiki-salata-greek-village-salad/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Helen Schofield, Scrummy Lane",
          "url": "https://scrummylane.com/perfect-greek-salad/",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Suzy Karadsheh, The Mediterranean Dish",
          "url": "https://shop.themediterraneandish.com/blogs/recipes/traditional-horiatiki-greek-salad",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "America's Test Kitchen",
          "url": "https://www.americastestkitchen.com/recipes/13158-horiatiki-salata-hearty-greek-salad",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Serious Eats",
          "url": "https://www.seriouseats.com/the-best-greek-salad-tomato-feta-summer-recipe",
          "lang": "en",
          "weight": 1
        }
      ]
    },
    "lemonates": {
      "researched": "2026-10-04",
      "sources": [
        {
          "name": "My Greek Dish",
          "url": "https://www.mygreekdish.com/recipe/crispiest-greek-lemon-potatoes-patates-lemonates/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Visit Greece (GNTO)",
          "url": "https://www.visitgreece.gr/el/experiences/gastronomy/recipes/baked-lemon-potatoes/",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "MamaPeinao",
          "url": "https://www.mamapeinao.gr/lemonates-patates/",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Ivy Liacopoulou, Kopiaste",
          "url": "https://www.kopiaste.info/2007/11/patates-lemonates-foyrno-i-sti-ladokolla/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "KitchenQueen",
          "url": "https://www.kitchenqueen.gr/",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Diane Kochilas, *The Food and Wine of Greece* (via Great Lent Gourmet)",
          "url": "http://greatlentgourmet.blogspot.com/2012/03/day-41-greek-style-oven-roasted.html",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Diane Kochilas, \"Yiayia's potatoes\"",
          "url": "https://www.dianekochilas.com/the-best-roasted-greek-yiayias-potatoes/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Dimitra's Dishes",
          "url": "https://www.dimitrasdishes.com/lemony-roasted-potatoes/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Vayia's Kitchen",
          "url": "https://vayiaskitchen.com/greek-style-lemon-roasted-potatoes/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Μαίρη Κωστόπουλου, Cookpad",
          "url": "https://cookpad.com/gr/sintages/24317901",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Argiro Barbarigou (via Mononews)",
          "url": "https://www.mononews.gr/city-stories/mpiftekia-afrata-me-lemonates-patates-sto-fourno-apo-tin-argiro-mparmparigou-video",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Herbs & Flour",
          "url": "https://herbsandflour.com/greek-lemon-potatoes-patates-lemonates-recipe/",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Xrysoskoufaki",
          "url": "https://xrysoskoufaki.gr/traganes-lemonates-patates-fournou/",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Nikolopaa",
          "url": "https://nikolopaa.com/greek-lemon-potatoes-recipe/",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Greek Cooking by Katerina",
          "url": "https://www.greekcookingbykaterina.com/recipes/recipe/59/patates-fournou",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Honest Cooking",
          "url": "https://honestcooking.com/easy-greek-lemon-potatoes/",
          "lang": "en",
          "weight": 0.5
        },
        {
          "name": "Mary Politis, Mary's Kouzina",
          "url": "https://www.maryskouzina.com/lemonates-patates-greek-lemon-potatoes/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Vefa Alexiadou (via Secret Kitchen and Travel)",
          "url": "https://secretkitchenandtravel.gr/patates-fournou-me-lemoni/",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Mitsomageiremata",
          "url": "https://www.mitsomageiremata.gr/menu-sintagon/patates/patates-fournou-lemonates-riganates-moustardates",
          "lang": "el",
          "weight": 1
        }
      ]
    },
    "melitzanosalata": {
      "researched": "2026-10-04",
      "sources": [
        {
          "name": "Argiro Barbarigou",
          "url": "https://www.argiro.gr/recipe/melitzanosalata/",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Ioanna Stamoulou / SKAI Cookout",
          "url": "https://cookout.skai.gr/recipes/melitzanosalata-klasiki",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Gogo / The Cook in You",
          "url": "https://thecookinyou.gr/efkoli-melitzanosalata/",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Katerina Moustaka",
          "url": "https://www.greekcookingbykaterina.com/recipes/recipe/255/melitzanosalata",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Ivy Liakopoulou / Kopiaste",
          "url": "https://www.kopiaste.info/2008/01/melitzanosalata-i-salata-melitzanes/",
          "lang": "el/en",
          "weight": 2
        },
        {
          "name": "Aggela Balabani on Cookpad GR, after Vefa Alexiadou",
          "url": "https://cookpad.com/gr/sintages/10655957-melitzana-salata-aloiphi",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Giorgio Spanakis / i-food",
          "url": "https://www.i-food.gr/recipe/5824/melitzanosalata-me-karidia",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Akis Petretzikis",
          "url": "https://akispetretzikis.com/recipe/2656/melitzanosalata",
          "lang": "el",
          "weight": 0.5
        },
        {
          "name": "Eli Giannopoulos / My Greek Dish",
          "url": "https://www.mygreekdish.com/recipe/melitzanosalata-aubergine-salad-dip/",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Dimitra Khan / Dimitra's Dishes",
          "url": "https://www.dimitrasdishes.com/melitzanosalata-greek-eggplant-dip-vegan/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Peter G / Souvlaki For The Soul",
          "url": "https://souvlakiforthesoul.com/melitzanosalata-recipe/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Nikolopaa",
          "url": "https://nikolopaa.com/melitzanosalata-recipe-greek-eggplant-dip/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Diane Kochilas",
          "url": "https://www.dianekochilas.com/melitzanosalata-me-kapari-kai-kremmydia-roasted-eggplant-salad-with-capers-and-onions/",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Fotini / Real Greek Recipes",
          "url": "https://realgreekrecipes.com/greek-eggplant-dip/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Maria / Authentic Greek Recipes (2008)",
          "url": "http://realgreekrecipes.blogspot.com/2008/03/eggplant-dip-melitzanosalata.html",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Filippo Trapella / Philosokitchen",
          "url": "https://philosokitchen.com/melitzanosalata-eggplant-recipe/",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Fin Moss / Ionian Gold",
          "url": "https://ioniangold.com/blogs/recipes/melitzanosalata",
          "lang": "en",
          "weight": 1
        }
      ]
    },
    "revithada": {
      "researched": "2026-10-04",
      "sources": [
        {
          "name": "Argiro Barbarigou, \"Ρεβυθάδα Σίφνου\"",
          "url": "https://argiro.gr/recipe/revythada-sifnou/",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "e-sifnos / Apostolidis Ceramics (Sifnos potter)",
          "url": "https://apostolidis-ceramics.gr/recipes.php",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Altis (olive-oil brand)",
          "url": "https://altis.com.gr/el-gr/recipe/rebuthada-siphnou-193451",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Vegan Times",
          "url": "https://vegantimes.gr/el/vegan-sintages/kirios-piata/revithada-sifnou/",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Giorgos Tsoulis",
          "url": "https://giorgostsoulis.com/syntages/ospria-ladera/sifneiki-revithada",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Dina Groumouthi, Athinorama Tasty",
          "url": "https://tasty.athinorama.gr/gourmet/fagito/2540753/_rebithada_sifneiki",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Stella Valourdou, nutri-book.gr",
          "url": "https://nutri-book.gr/syntages/ospria/rebithia-sto-pilino",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Dimitris Papazymouris, Cantina",
          "url": "https://cantina.protothema.gr/recipe/revithada-paradosiaki-sto-fourno/",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Konstantina Voulgareli, pandespani (via bovary.gr)",
          "url": "https://bovary.gr/living/taste/rebithada-sifnoy-se-pilino-syntagi",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Diane Kochilas",
          "url": "https://dianekochilas.com/clay-baked-chick-pea-soup/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Giorgos Grigoriadis (Narlis Farm, Sifnos), via gastronomytours.com",
          "url": "https://gastronomytours.com/encyclopedia/traditional-revithada-chickpea-stew-from-sifnos-by-george-grigoriadis/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Nikos Thomas, Bostani restaurant, Sifnos",
          "url": "https://verinahotelsifnos.com/taste-from-sifnos/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Angie, twominutesangie",
          "url": "https://twominutesangie.com/sifnos-revithada/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "George Zolis, Zoli's Kitchen",
          "url": "https://zoliskitchen.com/traditional-greek-chickpea-stew-revithia/recipe",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Damian Primis, Primis Imports",
          "url": "https://primisimports.com/blogs/recipes/revithada-sifnian-slow-baked-chickpeas",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Saltonomy",
          "url": "https://saltonomy.com/gastronomy/recipes/revithada-from-sifnos",
          "lang": "en",
          "weight": 0.5
        },
        {
          "name": "mypreptable",
          "url": "https://mypreptable.com/revithada-greek-baked-chickpeas/",
          "lang": "en",
          "weight": 0.5
        }
      ]
    },
    "skordalia": {
      "researched": "2026-10-04",
      "sources": [
        {
          "name": "Argiro Barbarigou",
          "url": "https://www.argiro.gr/recipe/skordalia/",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Akis Petretzikis",
          "url": "https://akispetretzikis.com/recipe/886/skordalia",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Giorgos Tsoulis",
          "url": "https://www.giorgostsoulis.com/syntages/saltses/skordalia-me-patata",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "MamaPeinao",
          "url": "https://www.mamapeinao.gr/skordalia/",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Ioanna Stamoulou, Cookout (SKAI)",
          "url": "https://cookout.skai.gr/recipes/skordalia-patatas",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "\"Κική\", Cookpad",
          "url": "https://cookpad.com/gr/sintages/4263120-skordalia-me-patata",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Τα φαγητά της γιαγιάς (blog)",
          "url": "https://faghta-giagias.blogspot.com/2012/10/blog-post_7094.html",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Greek Cooking by Katerina",
          "url": "https://www.greekcookingbykaterina.com/recipes/recipe/141/skordalia-paradosiaki-me-patata",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "The Issue (credits paxxi.gr)",
          "url": "https://www.theissue.gr/life/dyo-suntages-gia-tin-apoluti-skordalia-me-psomi-i-patata/",
          "lang": "el",
          "weight": 0.5
        },
        {
          "name": "iCookGreek (aliada)",
          "url": "https://www.icookgreek.com/istories/ftiachnoyme-aliada-skordalia-patata/",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Eli K. Giannopoulos, My Greek Dish",
          "url": "https://www.mygreekdish.com/recipe/greek-skordalia-recipe-potato-garlic-dip/",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Dimitra's Dishes",
          "url": "https://www.dimitrasdishes.com/skordalia-garlicky-lemony-mashed-potatoes/",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Fotini, Real Greek Recipes",
          "url": "https://realgreekrecipes.com/greek-garlic-and-potato-dip/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Mia Kouppa",
          "url": "https://miakouppa.com/recipe-skordalia/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Elena Paravantes, Olive Tomato",
          "url": "https://www.olivetomato.com/three-recipes-for-skordalia-greek-garlic-sauce-and-its-nutritional-value/",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Ivy Liacopoulou, Kopiaste",
          "url": "https://www.kopiaste.org/2008/01/skordalia/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Nicole Gaffney, Coley Cooks",
          "url": "https://coleycooks.com/skordalia/",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Steve Dunn, America's Test Kitchen",
          "url": "https://www.americastestkitchen.com/cooksillustrated/recipes/13544-skordalia-greek-garlic-potato-puree",
          "lang": "en",
          "weight": 1
        }
      ]
    },
    "soufico": {
      "researched": "2026-10-04",
      "sources": [
        {
          "name": "Diane Kochilas, \"Ikarian Soufico\"",
          "url": "https://dianekochilas.com/ikaria-soufico-blue-zone-longevity-recipe/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "ikarianews.gr (local Ikarian paper)",
          "url": "https://ikarianews.gr/archives/53099",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Ilias Mamalakis, Cantina",
          "url": "https://cantina.protothema.gr/recipe/soufiko-apo-tin-ikaria/",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Eva Monochari, Proto Thema",
          "url": "https://protothema.gr/recipes/article/1112608",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Altis (olive-oil brand)",
          "url": "https://altis.com.gr/el-gr/recipe/souphiko-ikarias-193832",
          "lang": "el",
          "weight": 0.5
        },
        {
          "name": "Argiro Glyka, Cookpad",
          "url": "https://cookpad.com/gr/sintages/16488305",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "\"Ρατατούλης της Ικαριακής\", Cookpad",
          "url": "https://cookpad.com/gr/sintages/3081662",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Antenna Europe, \"Η Ελλάδα στο πιάτο\"",
          "url": "https://antennaeurope.gr",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Dimitra Cherouvim, foodcollection.gr",
          "url": "https://foodcollection.gr/soufiko/",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "lykavitos.gr",
          "url": "https://lykavitos.gr/news/cooking/soufiko-10",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Meni Valle, *Ikaria: Food and Life in the Blue Zone* (ABC Life Matters)",
          "url": "https://abc.net.au/listen/programs/lifematters/ikaria-recipe:-soufiko/12615118",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Dimitra's Dishes",
          "url": "https://dimitrasdishes.com/soufiko-a-greek-summertime-stew/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Sarah Wilson",
          "url": "https://sarahwilson.com/2012/07/how-to-make-ikarian-soufiko/",
          "lang": "en",
          "weight": 1.5
        },
        {
          "name": "Stacie Billis",
          "url": "https://staciebillis.com/soufiko-recipe-greek-vegetable-stew-ikaria-blue-zone/",
          "lang": "en",
          "weight": 1.5
        },
        {
          "name": "Linda Hierholzer, Chef Sharing the Table",
          "url": "https://chefsharingthetable.com/home-blog/2018/1/8/soufiko",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Dan Buettner, \"Springtime Soufiko\"",
          "url": "https://danbuettner.com/recipes/springtime-soufiko/",
          "lang": "en",
          "weight": 0.5
        },
        {
          "name": "Alexandra's Home (TikTok @alexandras.home)",
          "url": "https://tiktok.com/@alexandras.home/video/7355939857862053162",
          "lang": "en",
          "weight": 2
        }
      ]
    },
    "spanakorizo": {
      "researched": "2026-10-04",
      "sources": [
        {
          "name": "Diane Kochilas",
          "url": "https://dianekochilas.com/spanakorizo-greek-spinach-rice/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Elena Paravantes, OliveTomato",
          "url": "https://olivetomato.com/greek-spinach-and-rice-spanakorizo/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Argiro Barbarigou (red version)",
          "url": "https://argiro.gr/recipe/spanakoryzo-kokkinisto/",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Giorgos Tsoulis",
          "url": "https://giorgostsoulis.com/syntages/ospria-ladera/spanakorizo",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Petros Syrigos",
          "url": "https://petros-syrigos.com/en/greek-spinach-and-rice-spanakorizo/",
          "lang": "el/en",
          "weight": 2
        },
        {
          "name": "iefimerida.gr (\"grandma's secrets\")",
          "url": "https://iefimerida.gr/gastronomie/syntagi-gia-spanakoryzo-ta-mystika-tis-giagias",
          "lang": "el",
          "weight": 0.5
        },
        {
          "name": "D. Papazimouris for Chryselia",
          "url": "https://xriselia.gr/recipe/to-lito-spanakoryzo-kai-ta-5-mystika-toy/",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Mia Kouppa (Bitzas sisters), red",
          "url": "https://miakouppa.com/spanakorizo/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Madame Ginger",
          "url": "https://madameginger.com",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Souvlaki For The Soul",
          "url": "https://souvlakiforthesoul.com/spanakorizo/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Dimitra's Dishes",
          "url": "https://dimitrasdishes.com/spanakorizo-greek-spinach-rice/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "My Greek Dish (red)",
          "url": "https://mygreekdish.com/recipe/greek-spinach-rice-recipe-spanakorizo/",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Real Greek Recipes",
          "url": "https://realgreekrecipes.com/greek-spinach-rice-spanakoryzo/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Akis Petretzikis (via snippets and a queen.gr copy)",
          "url": "https://akispetretzikis.com/recipe/5261/spanakoryzo",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Marilena's Kitchen",
          "url": "https://marilenaskitchen.com/easy-greek-spinach-and-rice-dish-spanakorizo/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Bovary.gr",
          "url": "https://bovary.gr/living/taste/syntagi-gia-spanakoryzo-san-tis-giagias",
          "lang": "el",
          "weight": 0.5
        },
        {
          "name": "Yiannis Lucacos (lemon version)",
          "url": "https://yiannislucacos.gr",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Olive & Mango",
          "url": "https://oliveandmango.com/spanakorizo-greek-spinach-rice/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Greek Cooking by Katerina",
          "url": "https://greekcookingbykaterina.com/recipes/recipe/110/spanakorizo",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Caroline's Cooking",
          "url": "https://carolinescooking.com/spanakorizo-greek-spinach-rice/",
          "lang": "en",
          "weight": 1
        }
      ]
    },
    "stifado": {
      "researched": "2026-10-04",
      "sources": [
        {
          "name": "Argiro Barbarigou, older recipe (with fried potatoes), as republished by syntagesmekefi / eirinika",
          "url": "https://www.syntagesmekefi.gr/2014/02/syntagi-stifado-moschari/",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Argiro Barbarigou, \"Στιφάδο της Αργυρώς\" (newer)",
          "url": "https://www.argiro.gr/recipe/stifado/",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Dimitra's Dishes (Dimitra Alfas)",
          "url": "https://www.dimitrasdishes.com/stifado-greek-beef-stew-with-shallots/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Real Greek Recipes",
          "url": "https://realgreekrecipes.com/stifado/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Greek Cooking by Katerina",
          "url": "https://www.greekcookingbykaterina.com/recipes/recipe/116/stifado-moschari",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Giorgos Tsoulis",
          "url": "https://www.giorgostsoulis.com/syntages/kyrios-gevmata/mosxari-stifado",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Mama Vasso, \"σμυρναίικο και ελαφρύ\"",
          "url": "https://mamavasso.me/moshari-stifado-smirneiko-elafri/",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Olive & Mango (Joanne Rappos)",
          "url": "https://www.oliveandmango.com/stifado-greek-beef-stew/",
          "lang": "en",
          "weight": 2
        },
        {
          "name": "Cantina / protothema (Ioanna Stamoulou)",
          "url": "https://cantina.protothema.gr/recipe/moscharaki-stifado/",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "paxxi (Eirini Zevelaki)",
          "url": "https://paxxi.gr/blog/stifado-mosxari/",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Christina Pavlou, clay pot",
          "url": "https://christinapavlou.gr/sintagi/moscharaki-stifado-sti-gastra/",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Kritikes Geuseis (Cretan recipe site)",
          "url": "https://www.kritikes-geuseis.gr/el/component/cobalt/item/5566-kreatika/1012-mosxaraki-stifado?Itemid=5587",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Caruso (chef's video recipe)",
          "url": "https://caruso.gr/mosxari-stifado/",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Hairy Bikers (via lovefood)",
          "url": "https://www.lovefood.com/recipes/56631/hairy-bikers-beef-stifado-recipe",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "My Greek Dish",
          "url": "https://www.mygreekdish.com/recipe/beef-stifado-mosharaki-stifado/",
          "lang": "en",
          "weight": 0.5
        },
        {
          "name": "newsit.gr / tasteit",
          "url": "https://www.newsit.gr/tasteit/syntagi-gia-paradosiako-mosxari-stifado/4503385/",
          "lang": "el",
          "weight": 0.5
        },
        {
          "name": "Make It Mediterranean (\"stifado-style\")",
          "url": "https://makeitmediterranean.com/greek-beef-stifado-style/",
          "lang": "en",
          "weight": 0.5
        },
        {
          "name": "Life with Zoe",
          "url": "https://lifewithzoe.com/beef-stifado/",
          "lang": "en",
          "weight": 0.5
        }
      ]
    },
    "tahinosoupa": {
      "researched": "2026-10-04",
      "sources": [
        {
          "name": "Monk Epifanios (Mount Athos head cook), via Mount Athos Legacy",
          "url": "https://mountathoslegacy.com/agioreitiki-tachinosoypa-syntagi-apo-ton-archimageira-toy-agioy-oroys-monacho-epifanio/",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Timoleon Diamantis",
          "url": "https://timoleondiamantis.gr/en/recipe/agioreitiki-tachinosoupa/",
          "lang": "el/en",
          "weight": 2
        },
        {
          "name": "Oliveology",
          "url": "https://oliveology.co.uk/tahinosoupa/",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "My Greek Food Recipes",
          "url": "https://www.mygreekfoodrecipes.com/2022/03/tahinosoupa-greek-tahini-soup.html",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "GreekBoston",
          "url": "https://www.greekboston.com/food/sesame-soup-recipe/",
          "lang": "en",
          "weight": 0.5
        },
        {
          "name": "Food.com (Cluich)",
          "url": "https://www.food.com/recipe/tahinosoupa-greek-tahini-soup-507235",
          "lang": "en",
          "weight": 0.5
        },
        {
          "name": "Eufrosaini, Cookpad, \"αλάδωτη της Μ. Παρασκευής\" (oil-free, for Good Friday)",
          "url": "https://cookpad.com/gr/sintages/12153775",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Georgia Mantzi (Alexandroupoli), Cookpad",
          "url": "https://cookpad.com/gr/sintages/14754709",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "dogma.gr, \"Αγιορείτικη ταχινόσουπα με ρύζι\"",
          "url": "https://www.dogma.gr/diafora/agioreitiki-tachinosoupa-me-ryzi/167712/",
          "lang": "el",
          "weight": 0.5
        },
        {
          "name": "Athinorama Tasty, \"Ταχινόσουπα αγιορείτικη\"",
          "url": "https://tasty.athinorama.gr/gourmet/almires-syntages/2003000/taxinosoupa_agioreitiki_",
          "lang": "el",
          "weight": 1
        },
        {
          "name": "Stella Foka (Cyprus), Cookpad",
          "url": "https://cookpad.com/gr/sintages/17296532",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Tessa Kiros, *Food from Many Greek Kitchens*, via FoodReference",
          "url": "https://www.foodreference.com/html/tahini-soup-recipe-112.html",
          "lang": "en",
          "weight": 1
        },
        {
          "name": "Akis Petretzikis",
          "url": "https://akispetretzikis.com/recipe/8924/tachinosoupa",
          "lang": "el",
          "weight": 2
        },
        {
          "name": "Carolina Doriti, Culinary Backstreets",
          "url": "https://culinarybackstreets.com/stories/athens/recipe-12",
          "lang": "en",
          "weight": 2
        }
      ]
    }
  }
};
