#!/usr/bin/env node
/*
 * build-sources.mjs — gather every recipe's sources into js/sources.js.
 *
 *     node tools/build-sources.mjs
 *
 * The research files (research/<kitchen>/<dish>.md) are the source of truth:
 * each has a "Sources" table of every recipe the consensus was built from,
 * with its author, link, language and weight. This reads those tables and
 * writes them out as plain data the recipe page can show — the same relation
 * tools/make-icons.py has to the icons. It compiles nothing and changes no
 * game code; re-run it whenever a research file changes, and commit both.
 *
 * Favourites carry their own `source` in js/favourites.js and are not read
 * here. A dish with no research file has no entry, and the page says so.
 */

import fs from "node:fs";
import path from "node:path";

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const out = {};

for (const kitchen of fs.readdirSync(path.join(root, "research"))) {
  const dir = path.join(root, "research", kitchen);
  if (!fs.statSync(dir).isDirectory()) continue;
  out[kitchen] = {};
  for (const file of fs.readdirSync(dir).filter((f) => f.endsWith(".md")).sort()) {
    const md = fs.readFileSync(path.join(dir, file), "utf8");
    // The Sources section only, up to the next heading, and in it only the
    // first table: later tables (amounts, method) are not sources.
    const after = md.split(/^## Sources\s*$/m)[1];
    if (!after) continue;
    const section = after.split(/^## /m)[0];
    const all = section.split("\n");
    const start = all.findIndex((l) => l.startsWith("|"));
    const lines = [];
    for (let i = start; i >= 0 && i < all.length && all[i].startsWith("|"); i++) lines.push(all[i]);
    const head = lines[0].split("|").map((c) => c.trim().toLowerCase());
    const col = (name) => head.findIndex((h) => h.startsWith(name));
    const [iName, iUrl, iLang, iWeight] = [col("author"), col("url"), col("lang"), col("weight")];
    const sources = [];
    for (const line of lines.slice(2)) {
      const cells = line.split("|").map((c) => c.trim());
      if (!cells[iName]) continue;
      // Links are written with or without the scheme; the first one counts.
      const raw = (cells[iUrl].match(/(https?:\/\/)?[a-z0-9.-]+\.[a-z]{2,}(\/[^\s·|)]*)?/i) || [""])[0].replace(/[),.]+$/, "");
      const url = raw && !/^https?:/.test(raw) ? "https://" + raw : raw;
      const weight = parseFloat(cells[iWeight]) || 1;
      sources.push({ name: cells[iName].replace(/\*\*/g, ""), url, lang: cells[iLang] || "", weight });
    }
    const dish = file.replace(/\.md$/, "");
    out[kitchen][dish] = { researched: (md.match(/\b(20\d\d-\d\d-\d\d)\b/) || [, ""])[1], sources };
  }
}

const header = `/*
 * sources.js — where every researched recipe came from. GENERATED by
 * tools/build-sources.mjs from research/<kitchen>/<dish>.md; do not edit by
 * hand, edit the research file and re-run the script.
 */
`;
fs.writeFileSync(path.join(root, "js/sources.js"), header + "export const SOURCES = " + JSON.stringify(out, null, 2) + ";\n");
const counts = Object.entries(out).map(([k, d]) => `${k}: ${Object.keys(d).length} dishes, ${Object.values(d).reduce((n, x) => n + x.sources.length, 0)} sources`);
console.log("wrote js/sources.js —", counts.join("; "));
